export const MENUS_PLAN = [
  {
    id: 1,
    nombre: "Menú 1 - CHO Bajos",
    tag: "CHO Bajos",
    totales: { kcal: 1464, proteina: 130.7, cho: 126.4, grasa: 49.7 },
    comidas: [
      {
        numero: "Comida 1",
        nombre: "Pericos + Arepa y Fresas",
        subtotal: { kcal: 321, proteina: 16.1, cho: 29.4, grasa: 15.9 },
        alimentos: [
          { nombre: "Huevo entero", cantidad: "2 huevos AA- Revueltos", kcal: 145, proteina: 13.0, cho: 1.0, grasa: 10.4 },
          { nombre: "Tomate", cantidad: "60 g", kcal: 11, proteina: 0.5, cho: 2.5, grasa: 0.0 },
          { nombre: "Cebolla larga", cantidad: "20 g", kcal: 6, proteina: 0.2, cho: 1.4, grasa: 0.0 },
          { nombre: "Aceite", cantidad: "5 g", kcal: 45, proteina: 0.0, cho: 0.0, grasa: 5.0 },
          { nombre: "Arepa de maíz", cantidad: "50 g", kcal: 82, proteina: 1.7, cho: 17.5, grasa: 0.5 },
          { nombre: "Fresas", cantidad: "100 g", kcal: 32, proteina: 0.7, cho: 7.0, grasa: 0.0 },
        ],
      },
      {
        numero: "Comida 2",
        nombre: "Arroz, pollo brócoli y aguacate",
        subtotal: { kcal: 545, proteina: 47.0, cho: 49.0, grasa: 17.8 },
        alimentos: [
          { nombre: "Pechuga pollo pesada cruda", cantidad: "170 g", kcal: 204, proteina: 38.0, cho: 0.0, grasa: 4.5 },
          { nombre: "Arroz blanco cocido", cantidad: "120 g", kcal: 156, proteina: 3.0, cho: 34.0, grasa: 0.3 },
          { nombre: "Brócoli", cantidad: "180 g", kcal: 60, proteina: 5.0, cho: 11.0, grasa: 0.5 },
          { nombre: "Aguacate", cantidad: "50 g", kcal: 80, proteina: 1.0, cho: 4.0, grasa: 7.5 },
          { nombre: "Aceite oliva", cantidad: "5 g", kcal: 45, proteina: 0.0, cho: 0.0, grasa: 5.0 },
        ],
      },
      {
        numero: "Comida 3",
        nombre: "Batido de proteina con Arandanos",
        subtotal: { kcal: 154, proteina: 24.5, cho: 11.0, grasa: 2.0 },
        alimentos: [
          { nombre: "Whey protein", cantidad: "30 g", kcal: 120, proteina: 24.0, cho: 3.0, grasa: 2.0 },
          { nombre: "Arándanos", cantidad: "60 g", kcal: 34, proteina: 0.5, cho: 8.0, grasa: 0.0 },
        ],
      },
      {
        numero: "Comida 4",
        nombre: "Lomo con papa y verduras",
        subtotal: { kcal: 444, proteina: 43.1, cho: 37.0, grasa: 14.0 },
        alimentos: [
          { nombre: "Lomo de cerdo pesado crudo", cantidad: "170 g", kcal: 241, proteina: 39.0, cho: 0.0, grasa: 9.0 },
          { nombre: "Papa cocida", cantidad: "120 g", kcal: 104, proteina: 2.0, cho: 24.0, grasa: 0.0 },
          { nombre: "Pimentón", cantidad: "80 g", kcal: 24, proteina: 1.0, cho: 6.0, grasa: 0.0 },
          { nombre: "Tomate", cantidad: "80 g", kcal: 14, proteina: 0.7, cho: 3.0, grasa: 0.0 },
          { nombre: "Cebolla", cantidad: "40 g", kcal: 16, proteina: 0.4, cho: 4.0, grasa: 0.0 },
          { nombre: "Aceite", cantidad: "5 g", kcal: 45, proteina: 0.0, cho: 0.0, grasa: 5.0 },
        ],
      },
    ],
  },
  {
    id: 2,
    nombre: "Menú 1 - CHO Moderados",
    tag: "CHO Moderados",
    totales: { kcal: 1639, proteina: 140.5, cho: 170.0, grasa: 44.4 },
    comidas: [
      {
        numero: "Comida 1",
        nombre: "Huevos revueltos con aguacate y pan integral y fruta",
        subtotal: { kcal: 444, proteina: 21.5, cho: 50.0, grasa: 18.4 },
        alimentos: [
          { nombre: "Pan integral", cantidad: "70 g", kcal: 175, proteina: 7.0, cho: 31.0, grasa: 2.0 },
          { nombre: "Huevo entero", cantidad: "2 huevos AA- Revueltos", kcal: 145, proteina: 13.0, cho: 1.0, grasa: 10.4 },
          { nombre: "Aguacate", cantidad: "40 g", kcal: 64, proteina: 1.0, cho: 3.0, grasa: 6.0 },
          { nombre: "Mango", cantidad: "100 g", kcal: 60, proteina: 0.5, cho: 15.0, grasa: 0.0 },
        ],
      },
      {
        numero: "Comida 2",
        nombre: "Pechuga de Pollo - Arroz y brocolí",
        subtotal: { kcal: 545, proteina: 50.0, cho: 60.0, grasa: 10.0 },
        alimentos: [
          { nombre: "Pechuga pollo cruda", cantidad: "180 g", kcal: 216, proteina: 41.0, cho: 0.0, grasa: 5.0 },
          { nombre: "Arroz cocido", cantidad: "180 g", kcal: 234, proteina: 5.0, cho: 50.0, grasa: 0.0 },
          { nombre: "Brócoli", cantidad: "150 g", kcal: 50, proteina: 4.0, cho: 10.0, grasa: 0.0 },
          { nombre: "Aceite oliva", cantidad: "5 g", kcal: 45, proteina: 0.0, cho: 0.0, grasa: 5.0 },
        ],
      },
      {
        numero: "Comida 3",
        nombre: "Batido de proteina con Fresas",
        subtotal: { kcal: 158, proteina: 25.0, cho: 12.0, grasa: 2.0 },
        alimentos: [
          { nombre: "Whey protein", cantidad: "30 g", kcal: 120, proteina: 24.0, cho: 3.0, grasa: 2.0 },
          { nombre: "Fresas", cantidad: "120 g", kcal: 38, proteina: 1.0, cho: 9.0, grasa: 0.0 },
        ],
      },
      {
        numero: "Comida 4",
        nombre: "Lomo con papa y verduras",
        subtotal: { kcal: 492, proteina: 44.0, cho: 48.0, grasa: 14.0 },
        alimentos: [
          { nombre: "Lomo cerdo crudo", cantidad: "170 g", kcal: 241, proteina: 39.0, cho: 0.0, grasa: 9.0 },
          { nombre: "Papa cocida", cantidad: "180 g", kcal: 156, proteina: 3.0, cho: 36.0, grasa: 0.0 },
          { nombre: "Pimentón", cantidad: "80 g", kcal: 24, proteina: 1.0, cho: 6.0, grasa: 0.0 },
          { nombre: "Tomate", cantidad: "80 g", kcal: 14, proteina: 0.7, cho: 3.0, grasa: 0.0 },
          { nombre: "Cebolla", cantidad: "30 g", kcal: 12, proteina: 0.3, cho: 3.0, grasa: 0.0 },
          { nombre: "Aceite", cantidad: "5 g", kcal: 45, proteina: 0.0, cho: 0.0, grasa: 5.0 },
        ],
      },
    ],
  },
  {
    id: 3,
    nombre: "Menú 2 - Bajos CHO",
    tag: "CHO Bajos",
    totales: { kcal: 1413, proteina: 144.7, cho: 93.8, grasa: 53.9 },
    comidas: [
      {
        numero: "Comida 1",
        nombre: "Huevos pericos con pan y fruta",
        subtotal: { kcal: 386, proteina: 19.3, cho: 40.8, grasa: 16.9 },
        alimentos: [
          { nombre: "Huevo doble AA", cantidad: "2 huevos", kcal: 145, proteina: 13.0, cho: 1.0, grasa: 10.4 },
          { nombre: "Tomate", cantidad: "70 g", kcal: 13, proteina: 0.6, cho: 3.0, grasa: 0.0 },
          { nombre: "Cebolla larga", cantidad: "25 g", kcal: 8, proteina: 0.2, cho: 1.8, grasa: 0.0 },
          { nombre: "Aceite", cantidad: "5 g", kcal: 45, proteina: 0.0, cho: 0.0, grasa: 5.0 },
          { nombre: "Pan integral", cantidad: "50 g", kcal: 125, proteina: 5.0, cho: 22.0, grasa: 1.5 },
          { nombre: "Piña", cantidad: "100 g", kcal: 50, proteina: 0.5, cho: 13.0, grasa: 0.0 },
        ],
      },
      {
        numero: "Comida 2",
        nombre: "Lomo de cerdo con ensalada de verduras",
        subtotal: { kcal: 481, proteina: 48.4, cho: 19.0, grasa: 25.0 },
        alimentos: [
          { nombre: "Lomo de cerdo crudo", cantidad: "190 g", kcal: 269, proteina: 44.0, cho: 0.0, grasa: 10.0 },
          { nombre: "Lechuga", cantidad: "120 g", kcal: 18, proteina: 1.2, cho: 4.0, grasa: 0.0 },
          { nombre: "Pepino", cantidad: "120 g", kcal: 19, proteina: 0.8, cho: 5.0, grasa: 0.0 },
          { nombre: "Tomate", cantidad: "100 g", kcal: 18, proteina: 1.0, cho: 4.0, grasa: 0.0 },
          { nombre: "Aguacate", cantidad: "70 g", kcal: 112, proteina: 1.4, cho: 6.0, grasa: 10.0 },
          { nombre: "Aceite oliva", cantidad: "5 g", kcal: 45, proteina: 0.0, cho: 0.0, grasa: 5.0 },
        ],
      },
      {
        numero: "Comida 3",
        nombre: "Batido de proteina con Fresas",
        subtotal: { kcal: 168, proteina: 25.0, cho: 14.0, grasa: 2.0 },
        alimentos: [
          { nombre: "Whey protein", cantidad: "30 g", kcal: 120, proteina: 24.0, cho: 3.0, grasa: 2.0 },
          { nombre: "Fresas", cantidad: "150 g", kcal: 48, proteina: 1.0, cho: 11.0, grasa: 0.0 },
        ],
      },
      {
        numero: "Comida 4",
        nombre: "Pechuga de pollo con verduras",
        subtotal: { kcal: 378, proteina: 52.0, cho: 20.0, grasa: 10.0 },
        alimentos: [
          { nombre: "Pechuga pollo cruda", cantidad: "190 g", kcal: 228, proteina: 43.0, cho: 0.0, grasa: 5.0 },
          { nombre: "Brócoli", cantidad: "180 g", kcal: 60, proteina: 5.0, cho: 11.0, grasa: 0.0 },
          { nombre: "Coliflor", cantidad: "180 g", kcal: 45, proteina: 4.0, cho: 9.0, grasa: 0.0 },
          { nombre: "Aceite de oliva", cantidad: "5 g", kcal: 45, proteina: 0.0, cho: 0.0, grasa: 5.0 },
        ],
      },
    ],
  },
  {
    id: 4,
    nombre: "Menú 3 - Bajos CHO",
    tag: "CHO Bajos",
    totales: { kcal: 1338, proteina: 124.5, cho: 86.8, grasa: 58.2 },
    comidas: [
      {
        numero: "Comida 1",
        nombre: "Huevos pericos con arepa y arandanos",
        subtotal: { kcal: 278, proteina: 15.8, cho: 30.8, grasa: 10.8 },
        alimentos: [
          { nombre: "Huevo entero doble A", cantidad: "2 huevos", kcal: 145, proteina: 13.0, cho: 1.0, grasa: 10.4 },
          { nombre: "Tomate", cantidad: "80 g", kcal: 14, proteina: 0.7, cho: 3.0, grasa: 0.0 },
          { nombre: "Cebolla larga", cantidad: "25 g", kcal: 8, proteina: 0.2, cho: 1.8, grasa: 0.0 },
          { nombre: "Arepa delgada", cantidad: "40 g", kcal: 66, proteina: 1.4, cho: 14.0, grasa: 0.4 },
          { nombre: "Arándanos", cantidad: "80 g", kcal: 45, proteina: 0.5, cho: 11.0, grasa: 0.0 },
        ],
      },
      {
        numero: "Comida 2",
        nombre: "Carne molida con verdura y aceite de oliva",
        subtotal: { kcal: 464, proteina: 46.0, cho: 22.0, grasa: 23.0 },
        alimentos: [
          { nombre: "Carne molida magra", cantidad: "180 g", kcal: 306, proteina: 36.0, cho: 0.0, grasa: 18.0 },
          { nombre: "Brócoli", cantidad: "200 g", kcal: 68, proteina: 6.0, cho: 13.0, grasa: 0.0 },
          { nombre: "Coliflor", cantidad: "180 g", kcal: 45, proteina: 4.0, cho: 9.0, grasa: 0.0 },
          { nombre: "Aceite oliva", cantidad: "5 g", kcal: 45, proteina: 0.0, cho: 0.0, grasa: 5.0 },
        ],
      },
      {
        numero: "Comida 3",
        nombre: "Huevos cocidos con fruta",
        subtotal: { kcal: 205, proteina: 13.5, cho: 16.0, grasa: 10.4 },
        alimentos: [
          { nombre: "Huevo entero cocido", cantidad: "2 unid (100 g)", kcal: 145, proteina: 13.0, cho: 1.0, grasa: 10.4 },
          { nombre: "Piña", cantidad: "120 g", kcal: 60, proteina: 0.5, cho: 15.0, grasa: 0.0 },
        ],
      },
      {
        numero: "Comida 4",
        nombre: "Pechuga de pollo con ensalada y aguacate",
        subtotal: { kcal: 391, proteina: 49.2, cho: 18.0, grasa: 14.0 },
        alimentos: [
          { nombre: "Pechuga pollo cruda", cantidad: "200 g", kcal: 240, proteina: 45.0, cho: 0.0, grasa: 5.0 },
          { nombre: "Lechuga", cantidad: "120 g", kcal: 18, proteina: 1.2, cho: 4.0, grasa: 0.0 },
          { nombre: "Pepino", cantidad: "120 g", kcal: 19, proteina: 0.8, cho: 5.0, grasa: 0.0 },
          { nombre: "Tomate", cantidad: "100 g", kcal: 18, proteina: 1.0, cho: 4.0, grasa: 0.0 },
          { nombre: "Aguacate", cantidad: "60 g", kcal: 96, proteina: 1.2, cho: 5.0, grasa: 9.0 },
        ],
      },
    ],
  },
  {
    id: 5,
    nombre: "Menú 4 - Bajos CHO",
    tag: "CHO Bajos",
    totales: { kcal: 1528, proteina: 113.0, cho: 164.3, grasa: 45.8 },
    comidas: [
      {
        numero: "Comida 1",
        nombre: "Pancakes de Avena con huevo",
        subtotal: { kcal: 341, proteina: 18.3, cho: 40.0, grasa: 12.4 },
        alimentos: [
          { nombre: "Huevo entero Doble A", cantidad: "2 huevos", kcal: 145, proteina: 13.0, cho: 1.0, grasa: 10.4 },
          { nombre: "Avena", cantidad: "30 g", kcal: 114, proteina: 4.0, cho: 20.0, grasa: 2.0 },
          { nombre: "Banano", cantidad: "50 g", kcal: 50, proteina: 0.6, cho: 12.0, grasa: 0.0 },
          { nombre: "Fresas", cantidad: "100 g", kcal: 32, proteina: 0.7, cho: 7.0, grasa: 0.0 },
        ],
      },
      {
        numero: "Comida 2",
        nombre: "Bowl de yogurt griego con fruta",
        subtotal: { kcal: 289, proteina: 13.4, cho: 31.8, grasa: 12.4 },
        alimentos: [
          { nombre: "Yogurt griego Dejamu", cantidad: "170 g", kcal: 168, proteina: 10.9, cho: 8.8, grasa: 10.0 },
          { nombre: "Arándanos", cantidad: "80 g", kcal: 45, proteina: 0.5, cho: 11.0, grasa: 0.0 },
          { nombre: "Mango", cantidad: "60 g", kcal: 36, proteina: 0.4, cho: 9.0, grasa: 0.0 },
          { nombre: "Chía", cantidad: "8 g", kcal: 40, proteina: 1.6, cho: 3.0, grasa: 2.4 },
        ],
      },
      {
        numero: "Comida 3",
        nombre: "Hamburgesa casera",
        subtotal: { kcal: 534, proteina: 38.9, cho: 55.5, grasa: 17.0 },
        alimentos: [
          { nombre: "Carne molida magra", cantidad: "150 g", kcal: 255, proteina: 30.0, cho: 0.0, grasa: 15.0 },
          { nombre: "Pan hamburguesa", cantidad: "60 g", kcal: 158, proteina: 6.0, cho: 28.0, grasa: 2.0 },
          { nombre: "Papa en air fryer", cantidad: "120 g", kcal: 104, proteina: 2.0, cho: 24.0, grasa: 0.0 },
          { nombre: "Lechuga", cantidad: "40 g", kcal: 6, proteina: 0.4, cho: 1.0, grasa: 0.0 },
          { nombre: "Tomate", cantidad: "60 g", kcal: 11, proteina: 0.5, cho: 2.5, grasa: 0.0 },
        ],
      },
      {
        numero: "Comida 4",
        nombre: "Pechuga de pollo con papa, Ahuyama y verduras",
        subtotal: { kcal: 364, proteina: 42.4, cho: 37.0, grasa: 4.0 },
        alimentos: [
          { nombre: "Pechuga pollo", cantidad: "170 g", kcal: 204, proteina: 39.0, cho: 0.0, grasa: 4.0 },
          { nombre: "Papa", cantidad: "80 g", kcal: 70, proteina: 1.6, cho: 16.0, grasa: 0.0 },
          { nombre: "Ahuyama", cantidad: "150 g", kcal: 53, proteina: 1.0, cho: 12.0, grasa: 0.0 },
          { nombre: "Zanahoria", cantidad: "60 g", kcal: 25, proteina: 0.5, cho: 6.0, grasa: 0.0 },
          { nombre: "Cebolla", cantidad: "30 g", kcal: 12, proteina: 0.3, cho: 3.0, grasa: 0.0 },
        ],
      },
    ],
  },
  {
    id: 6,
    nombre: "Menú 2 - Medios CHO",
    tag: "CHO Moderados",
    totales: { kcal: 1635, proteina: 123.2, cho: 171.8, grasa: 51.3 },
    comidas: [
      {
        numero: "Comida 1",
        nombre: "Wrap de Huevo y vegetales   con fruta",
        subtotal: { kcal: 378, proteina: 25.2, cho: 38.5, grasa: 14.4 },
        alimentos: [
          { nombre: "Pan integral", cantidad: "60 g", kcal: 150, proteina: 6.0, cho: 27.0, grasa: 2.0 },
          { nombre: "Huevo entero", cantidad: "100 g", kcal: 145, proteina: 13.0, cho: 1.0, grasa: 10.4 },
          { nombre: "Queso mozzarella light", cantidad: "20 g", kcal: 40, proteina: 5.0, cho: 1.0, grasa: 2.0 },
          { nombre: "Tomate", cantidad: "60 g", kcal: 11, proteina: 0.5, cho: 2.5, grasa: 0.0 },
          { nombre: "Fresas", cantidad: "100 g", kcal: 32, proteina: 0.7, cho: 7.0, grasa: 0.0 },
        ],
      },
      {
        numero: "Comida 2",
        nombre: "Pechuga de pollo con arroz y vegetales",
        subtotal: { kcal: 499, proteina: 48.5, cho: 56.0, grasa: 9.0 },
        alimentos: [
          { nombre: "Pechuga pollo cruda", cantidad: "170 g", kcal: 187, proteina: 39.0, cho: 0.0, grasa: 4.0 },
          { nombre: "Arroz blanco cocido", cantidad: "140 g", kcal: 182, proteina: 4.0, cho: 39.0, grasa: 0.0 },
          { nombre: "Brócoli", cantidad: "180 g", kcal: 60, proteina: 5.0, cho: 11.0, grasa: 0.0 },
          { nombre: "Zanahoria", cantidad: "60 g", kcal: 25, proteina: 0.5, cho: 6.0, grasa: 0.0 },
          { nombre: "Aceite oliva", cantidad: "5 g", kcal: 45, proteina: 0.0, cho: 0.0, grasa: 5.0 },
        ],
      },
      {
        numero: "Comida 3",
        nombre: "Bowl de Avena con fruta",
        subtotal: { kcal: 284, proteina: 13.6, cho: 30.8, grasa: 11.9 },
        alimentos: [
          { nombre: "Yogurt griego Dejamu", cantidad: "150 g", kcal: 149, proteina: 9.6, cho: 7.8, grasa: 8.9 },
          { nombre: "Arándanos", cantidad: "60 g", kcal: 34, proteina: 0.5, cho: 8.0, grasa: 0.0 },
          { nombre: "Avena", cantidad: "20 g", kcal: 76, proteina: 2.5, cho: 13.0, grasa: 1.5 },
          { nombre: "Chía", cantidad: "5 g", kcal: 25, proteina: 1.0, cho: 2.0, grasa: 1.5 },
        ],
      },
      {
        numero: "Comida 4",
        nombre: "Hamburguesa casera con papa en Air Fryer",
        subtotal: { kcal: 474, proteina: 35.9, cho: 46.5, grasa: 16.0 },
        alimentos: [
          { nombre: "Carne molida magra", cantidad: "140 g", kcal: 238, proteina: 28.0, cho: 0.0, grasa: 14.0 },
          { nombre: "Pan hamburguesa", cantidad: "50 g", kcal: 132, proteina: 5.0, cho: 23.0, grasa: 2.0 },
          { nombre: "Papa en air fryer", cantidad: "100 g", kcal: 87, proteina: 2.0, cho: 20.0, grasa: 0.0 },
          { nombre: "Lechuga", cantidad: "40 g", kcal: 6, proteina: 0.4, cho: 1.0, grasa: 0.0 },
          { nombre: "Tomate", cantidad: "60 g", kcal: 11, proteina: 0.5, cho: 2.5, grasa: 0.0 },
        ],
      },
    ],
  },
  {
    id: 7,
    nombre: "Menú 3 - Medios CHO",
    tag: "CHO Moderados",
    totales: { kcal: 1804, proteina: 148.6, cho: 188.3, grasa: 51.5 },
    comidas: [
      {
        numero: "Comida 1",
        nombre: "Arepas con huevo, aguacate y tomate",
        subtotal: { kcal: 412, proteina: 20.1, cho: 39.5, grasa: 20.5 },
        alimentos: [
          { nombre: "Arepa delgada", cantidad: "90 g", kcal: 147, proteina: 3.0, cho: 32.0, grasa: 1.0 },
          { nombre: "Huevo entero", cantidad: "120 g", kcal: 174, proteina: 15.6, cho: 1.0, grasa: 12.5 },
          { nombre: "Aguacate", cantidad: "50 g", kcal: 80, proteina: 1.0, cho: 4.0, grasa: 7.0 },
          { nombre: "Tomate", cantidad: "60 g", kcal: 11, proteina: 0.5, cho: 2.5, grasa: 0.0 },
        ],
      },
      {
        numero: "Comida 2",
        nombre: "Pasta con Lomo de cerdo y vegetales",
        subtotal: { kcal: 589, proteina: 50.5, cho: 61.0, grasa: 15.0 },
        alimentos: [
          { nombre: "Pasta cocida", cantidad: "160 g", kcal: 246, proteina: 8.0, cho: 50.0, grasa: 1.0 },
          { nombre: "Lomo de cerdo crudo", cantidad: "180 g", kcal: 254, proteina: 41.0, cho: 0.0, grasa: 9.0 },
          { nombre: "Pimentón", cantidad: "80 g", kcal: 24, proteina: 1.0, cho: 6.0, grasa: 0.0 },
          { nombre: "Cebolla", cantidad: "50 g", kcal: 20, proteina: 0.5, cho: 5.0, grasa: 0.0 },
          { nombre: "Aceite oliva", cantidad: "5 g", kcal: 45, proteina: 0.0, cho: 0.0, grasa: 5.0 },
        ],
      },
      {
        numero: "Comida 3",
        nombre: "Bowl de Yogurt griego con fruta y Whey protein",
        subtotal: { kcal: 354, proteina: 36.2, cho: 27.8, grasa: 12.0 },
        alimentos: [
          { nombre: "Yogurt griego Dejamu", cantidad: "170 g", kcal: 168, proteina: 10.9, cho: 8.8, grasa: 10.0 },
          { nombre: "Whey protein", cantidad: "30 g", kcal: 120, proteina: 24.0, cho: 3.0, grasa: 2.0 },
          { nombre: "Fresas", cantidad: "120 g", kcal: 38, proteina: 1.0, cho: 9.0, grasa: 0.0 },
          { nombre: "Arándanos", cantidad: "50 g", kcal: 28, proteina: 0.3, cho: 7.0, grasa: 0.0 },
        ],
      },
      {
        numero: "Comida 4",
        nombre: "Sopa espesa con pollo y papa",
        subtotal: { kcal: 449, proteina: 41.8, cho: 60.0, grasa: 4.0 },
        alimentos: [
          { nombre: "Pechuga pollo desmechada", cantidad: "160 g", kcal: 192, proteina: 37.0, cho: 0.0, grasa: 4.0 },
          { nombre: "Papa cocida", cantidad: "180 g", kcal: 156, proteina: 3.0, cho: 36.0, grasa: 0.0 },
          { nombre: "Ahuyama", cantidad: "180 g", kcal: 64, proteina: 1.0, cho: 15.0, grasa: 0.0 },
          { nombre: "Zanahoria", cantidad: "60 g", kcal: 25, proteina: 0.5, cho: 6.0, grasa: 0.0 },
          { nombre: "Cebolla", cantidad: "30 g", kcal: 12, proteina: 0.3, cho: 3.0, grasa: 0.0 },
        ],
      },
    ],
  },
  {
    id: 8,
    nombre: "Menú 5 - Bajos CHO",
    tag: "CHO Bajos",
    totales: { kcal: 1414, proteina: 132.9, cho: 138.3, grasa: 38.0 },
    comidas: [
      {
        numero: "Comida 1",
        nombre: "Huevos pericos con arepa y fruta",
        subtotal: { kcal: 307, proteina: 18.8, cho: 30.3, grasa: 13.0 },
        alimentos: [
          { nombre: "Huevo entero", cantidad: "120 g", kcal: 174, proteina: 15.6, cho: 1.0, grasa: 12.5 },
          { nombre: "Tomate", cantidad: "60 g", kcal: 11, proteina: 0.5, cho: 2.5, grasa: 0.0 },
          { nombre: "Cebolla larga", cantidad: "25 g", kcal: 8, proteina: 0.3, cho: 1.8, grasa: 0.0 },
          { nombre: "Arepa delgada", cantidad: "50 g", kcal: 82, proteina: 1.7, cho: 18.0, grasa: 0.5 },
          { nombre: "Fresas", cantidad: "100 g", kcal: 32, proteina: 0.7, cho: 7.0, grasa: 0.0 },
        ],
      },
      {
        numero: "Comida 2",
        nombre: "Carne asada con papa criolla y ensalada",
        subtotal: { kcal: 450, proteina: 42.0, cho: 35.0, grasa: 15.0 },
        alimentos: [
          { nombre: "Carne de res magra", cantidad: "170 g", kcal: 290, proteina: 38.0, cho: 0.0, grasa: 15.0 },
          { nombre: "Papa criolla cocida", cantidad: "120 g", kcal: 120, proteina: 2.0, cho: 26.0, grasa: 0.0 },
          { nombre: "Lechuga", cantidad: "60 g", kcal: 10, proteina: 0.7, cho: 2.0, grasa: 0.0 },
          { nombre: "Tomate", cantidad: "80 g", kcal: 14, proteina: 0.7, cho: 3.0, grasa: 0.0 },
          { nombre: "Pepino", cantidad: "100 g", kcal: 16, proteina: 0.6, cho: 4.0, grasa: 0.0 },
        ],
      },
      {
        numero: "Comida 3",
        nombre: "Whey Protein con fruta",
        subtotal: { kcal: 228, proteina: 25.3, cho: 30.0, grasa: 2.0 },
        alimentos: [
          { nombre: "Whey protein", cantidad: "30 g", kcal: 120, proteina: 24.0, cho: 3.0, grasa: 2.0 },
          { nombre: "Banano", cantidad: "80 g", kcal: 80, proteina: 1.0, cho: 20.0, grasa: 0.0 },
          { nombre: "Arándanos", cantidad: "50 g", kcal: 28, proteina: 0.3, cho: 7.0, grasa: 0.0 },
        ],
      },
      {
        numero: "Comida 2",
        nombre: "Higado encebollado de Res con ahuyama y brocolí",
        subtotal: { kcal: 429, proteina: 46.8, cho: 43.0, grasa: 8.0 },
        alimentos: [
          { nombre: "Hígado de res", cantidad: "200 g", kcal: 270, proteina: 40.0, cho: 8.0, grasa: 8.0 },
          { nombre: "Cebolla", cantidad: "60 g", kcal: 24, proteina: 0.6, cho: 6.0, grasa: 0.0 },
          { nombre: "Tomate", cantidad: "80 g", kcal: 14, proteina: 0.7, cho: 3.0, grasa: 0.0 },
          { nombre: "Ahuyama cocida", cantidad: "200 g", kcal: 71, proteina: 1.5, cho: 16.0, grasa: 0.0 },
          { nombre: "Brócoli", cantidad: "150 g", kcal: 50, proteina: 4.0, cho: 10.0, grasa: 0.0 },
        ],
      },
    ],
  }
] as const

export type MenuPlan = typeof MENUS_PLAN[number]
