// Generado automáticamente — no editar manualmente
export const MENUS_PLAN = [
  {
    id: 1,
    nombre: "Menú 1 - CHO Bajos",
    tag: "CHO Bajos",
    totales: { kcal: 1464, proteina: 130.7, cho: 126.4, grasa: 49.7 },
    comidas: [
      {
        numero: "Comida 1",
        nombre: "Pericos + Arepa y Fresas",
        subtotal: { kcal: 321, proteina: 16.1, cho: 29.4, grasa: 15.9 },
        alimentos: [
          { nombre: "Huevo entero", cantidad: "2 huevos AA- Revueltos", kcal: 145, proteina: 13.0, cho: 1.0, grasa: 10.4, esLibre: false },
          { nombre: "Tomate", cantidad: "60 g", kcal: 11, proteina: 0.5, cho: 2.5, grasa: 0, esLibre: false },
          { nombre: "Cebolla larga", cantidad: "20 g", kcal: 6, proteina: 0.2, cho: 1.4, grasa: 0, esLibre: false },
          { nombre: "Aceite", cantidad: "5 g", kcal: 45, proteina: 0, cho: 0, grasa: 5.0, esLibre: false },
          { nombre: "Arepa de maíz", cantidad: "50 g", kcal: 82, proteina: 1.7, cho: 17.5, grasa: 0.5, esLibre: false },
          { nombre: "Fresas", cantidad: "100 g", kcal: 32, proteina: 0.7, cho: 7.0, grasa: 0, esLibre: false },
        ],
      },
      {
        numero: "Comida 2",
        nombre: "Arroz, pollo brócoli y aguacate",
        subtotal: { kcal: 545, proteina: 47.0, cho: 49.0, grasa: 17.8 },
        alimentos: [
          { nombre: "Pechuga pollo pesada cruda", cantidad: "170 g", kcal: 204, proteina: 38.0, cho: 0, grasa: 4.5, esLibre: false },
          { nombre: "Arroz blanco cocido", cantidad: "120 g", kcal: 156, proteina: 3.0, cho: 34.0, grasa: 0.3, esLibre: false },
          { nombre: "Brócoli", cantidad: "180 g", kcal: 60, proteina: 5.0, cho: 11.0, grasa: 0.5, esLibre: false },
          { nombre: "Aguacate", cantidad: "50 g", kcal: 80, proteina: 1.0, cho: 4.0, grasa: 7.5, esLibre: false },
          { nombre: "Aceite oliva", cantidad: "5 g", kcal: 45, proteina: 0, cho: 0, grasa: 5.0, esLibre: false },
        ],
      },
      {
        numero: "Comida 3",
        nombre: "Batido de proteina con Arandanos",
        subtotal: { kcal: 154, proteina: 24.5, cho: 11.0, grasa: 2.0 },
        alimentos: [
          { nombre: "Whey protein", cantidad: "30 g", kcal: 120, proteina: 24.0, cho: 3.0, grasa: 2.0, esLibre: false },
          { nombre: "Arándanos", cantidad: "60 g", kcal: 34, proteina: 0.5, cho: 8.0, grasa: 0, esLibre: false },
        ],
      },
      {
        numero: "Comida 4",
        nombre: "Lomo con papa y verduras",
        subtotal: { kcal: 444, proteina: 43.1, cho: 37.0, grasa: 14.0 },
        alimentos: [
          { nombre: "Lomo de cerdo pesado crudo", cantidad: "170 g", kcal: 241, proteina: 39.0, cho: 0, grasa: 9.0, esLibre: false },
          { nombre: "Papa cocida", cantidad: "120 g", kcal: 104, proteina: 2.0, cho: 24.0, grasa: 0, esLibre: false },
          { nombre: "Pimentón", cantidad: "80 g", kcal: 24, proteina: 1.0, cho: 6.0, grasa: 0, esLibre: false },
          { nombre: "Tomate", cantidad: "80 g", kcal: 14, proteina: 0.7, cho: 3.0, grasa: 0, esLibre: false },
          { nombre: "Cebolla", cantidad: "40 g", kcal: 16, proteina: 0.4, cho: 4.0, grasa: 0, esLibre: false },
          { nombre: "Aceite", cantidad: "5 g", kcal: 45, proteina: 0, cho: 0, grasa: 5.0, esLibre: false },
        ],
      },
    ],
  },
  {
    id: 2,
    nombre: "Menú 1 - CHO Moderados",
    tag: "CHO Moderados",
    totales: { kcal: 1639, proteina: 140.5, cho: 170.0, grasa: 44.4 },
    comidas: [
      {
        numero: "Comida 1",
        nombre: "Huevos revueltos con aguacate y pan integral y fruta",
        subtotal: { kcal: 444, proteina: 21.5, cho: 50.0, grasa: 18.4 },
        alimentos: [
          { nombre: "Pan integral", cantidad: "70 g", kcal: 175, proteina: 7.0, cho: 31.0, grasa: 2.0, esLibre: false },
          { nombre: "Huevo entero", cantidad: "2 huevos AA- Revueltos", kcal: 145, proteina: 13.0, cho: 1.0, grasa: 10.4, esLibre: false },
          { nombre: "Aguacate", cantidad: "40 g", kcal: 64, proteina: 1.0, cho: 3.0, grasa: 6.0, esLibre: false },
          { nombre: "Mango", cantidad: "100 g", kcal: 60, proteina: 0.5, cho: 15.0, grasa: 0, esLibre: false },
        ],
      },
      {
        numero: "Comida 2",
        nombre: "Pechuga de Pollo - Arroz y brocolí",
        subtotal: { kcal: 545, proteina: 50.0, cho: 60.0, grasa: 10.0 },
        alimentos: [
          { nombre: "Pechuga pollo cruda", cantidad: "180 g", kcal: 216, proteina: 41.0, cho: 0, grasa: 5.0, esLibre: false },
          { nombre: "Arroz cocido", cantidad: "180 g", kcal: 234, proteina: 5.0, cho: 50.0, grasa: 0, esLibre: false },
          { nombre: "Brócoli", cantidad: "150 g", kcal: 50, proteina: 4.0, cho: 10.0, grasa: 0, esLibre: false },
          { nombre: "Aceite oliva", cantidad: "5 g", kcal: 45, proteina: 0, cho: 0, grasa: 5.0, esLibre: false },
        ],
      },
      {
        numero: "Comida 3",
        nombre: "Batido de proteina con Fresas",
        subtotal: { kcal: 158, proteina: 25.0, cho: 12.0, grasa: 2.0 },
        alimentos: [
          { nombre: "Whey protein", cantidad: "30 g", kcal: 120, proteina: 24.0, cho: 3.0, grasa: 2.0, esLibre: false },
          { nombre: "Fresas", cantidad: "120 g", kcal: 38, proteina: 1.0, cho: 9.0, grasa: 0, esLibre: false },
        ],
      },
      {
        numero: "Comida 4",
        nombre: "Lomo con papa y verduras",
        subtotal: { kcal: 492, proteina: 44.0, cho: 48.0, grasa: 14.0 },
        alimentos: [
          { nombre: "Lomo cerdo crudo", cantidad: "170 g", kcal: 241, proteina: 39.0, cho: 0, grasa: 9.0, esLibre: false },
          { nombre: "Papa cocida", cantidad: "180 g", kcal: 156, proteina: 3.0, cho: 36.0, grasa: 0, esLibre: false },
          { nombre: "Pimentón", cantidad: "80 g", kcal: 24, proteina: 1.0, cho: 6.0, grasa: 0, esLibre: false },
          { nombre: "Tomate", cantidad: "80 g", kcal: 14, proteina: 0.7, cho: 3.0, grasa: 0, esLibre: false },
          { nombre: "Cebolla", cantidad: "30 g", kcal: 12, proteina: 0.3, cho: 3.0, grasa: 0, esLibre: false },
          { nombre: "Aceite", cantidad: "5 g", kcal: 45, proteina: 0, cho: 0, grasa: 5.0, esLibre: false },
        ],
      },
    ],
  },
  {
    id: 3,
    nombre: "Menú 2 - Bajos CHO",
    tag: "CHO Bajos",
    totales: { kcal: 1413, proteina: 144.7, cho: 93.8, grasa: 53.9 },
    comidas: [
      {
        numero: "Comida 1",
        nombre: "Huevos pericos con pan y fruta",
        subtotal: { kcal: 386, proteina: 19.3, cho: 40.8, grasa: 16.9 },
        alimentos: [
          { nombre: "Huevo doble AA", cantidad: "2 huevos", kcal: 145, proteina: 13.0, cho: 1.0, grasa: 10.4, esLibre: false },
          { nombre: "Tomate", cantidad: "70 g", kcal: 13, proteina: 0.6, cho: 3.0, grasa: 0, esLibre: false },
          { nombre: "Cebolla larga", cantidad: "25 g", kcal: 8, proteina: 0.2, cho: 1.8, grasa: 0, esLibre: false },
          { nombre: "Aceite", cantidad: "5 g", kcal: 45, proteina: 0, cho: 0, grasa: 5.0, esLibre: false },
          { nombre: "Pan integral", cantidad: "50 g", kcal: 125, proteina: 5.0, cho: 22.0, grasa: 1.5, esLibre: false },
          { nombre: "Piña", cantidad: "100 g", kcal: 50, proteina: 0.5, cho: 13.0, grasa: 0, esLibre: false },
        ],
      },
      {
        numero: "Comida 2",
        nombre: "Lomo de cerdo con ensalada de verduras",
        subtotal: { kcal: 481, proteina: 48.4, cho: 19.0, grasa: 25.0 },
        alimentos: [
          { nombre: "Lomo de cerdo crudo", cantidad: "190 g", kcal: 269, proteina: 44.0, cho: 0, grasa: 10.0, esLibre: false },
          { nombre: "Lechuga", cantidad: "120 g", kcal: 18, proteina: 1.2, cho: 4.0, grasa: 0, esLibre: false },
          { nombre: "Pepino", cantidad: "120 g", kcal: 19, proteina: 0.8, cho: 5.0, grasa: 0, esLibre: false },
          { nombre: "Tomate", cantidad: "100 g", kcal: 18, proteina: 1.0, cho: 4.0, grasa: 0, esLibre: false },
          { nombre: "Aguacate", cantidad: "70 g", kcal: 112, proteina: 1.4, cho: 6.0, grasa: 10.0, esLibre: false },
          { nombre: "Aceite oliva", cantidad: "5 g", kcal: 45, proteina: 0, cho: 0, grasa: 5.0, esLibre: false },
        ],
      },
      {
        numero: "Comida 3",
        nombre: "Batido de proteina con Fresas",
        subtotal: { kcal: 168, proteina: 25.0, cho: 14.0, grasa: 2.0 },
        alimentos: [
          { nombre: "Whey protein", cantidad: "30 g", kcal: 120, proteina: 24.0, cho: 3.0, grasa: 2.0, esLibre: false },
          { nombre: "Fresas", cantidad: "150 g", kcal: 48, proteina: 1.0, cho: 11.0, grasa: 0, esLibre: false },
        ],
      },
      {
        numero: "Comida 4",
        nombre: "Pechuga de pollo con verduras",
        subtotal: { kcal: 378, proteina: 52.0, cho: 20.0, grasa: 10.0 },
        alimentos: [
          { nombre: "Pechuga pollo cruda", cantidad: "190 g", kcal: 228, proteina: 43.0, cho: 0, grasa: 5.0, esLibre: false },
          { nombre: "Brócoli", cantidad: "180 g", kcal: 60, proteina: 5.0, cho: 11.0, grasa: 0, esLibre: false },
          { nombre: "Coliflor", cantidad: "180 g", kcal: 45, proteina: 4.0, cho: 9.0, grasa: 0, esLibre: false },
          { nombre: "Aceite de oliva", cantidad: "5 g", kcal: 45, proteina: 0, cho: 0, grasa: 5.0, esLibre: false },
        ],
      },
    ],
  },
  {
    id: 4,
    nombre: "Menú 3 - Bajos CHO",
    tag: "CHO Bajos",
    totales: { kcal: 1338, proteina: 124.5, cho: 86.8, grasa: 58.2 },
    comidas: [
      {
        numero: "Comida 1",
        nombre: "Huevos pericos con arepa y arandanos",
        subtotal: { kcal: 278, proteina: 15.8, cho: 30.8, grasa: 10.8 },
        alimentos: [
          { nombre: "Huevo entero doble A", cantidad: "2 huevos", kcal: 145, proteina: 13.0, cho: 1.0, grasa: 10.4, esLibre: false },
          { nombre: "Tomate", cantidad: "80 g", kcal: 14, proteina: 0.7, cho: 3.0, grasa: 0, esLibre: false },
          { nombre: "Cebolla larga", cantidad: "25 g", kcal: 8, proteina: 0.2, cho: 1.8, grasa: 0, esLibre: false },
          { nombre: "Arepa delgada", cantidad: "40 g", kcal: 66, proteina: 1.4, cho: 14.0, grasa: 0.4, esLibre: false },
          { nombre: "Arándanos", cantidad: "80 g", kcal: 45, proteina: 0.5, cho: 11.0, grasa: 0, esLibre: false },
        ],
      },
      {
        numero: "Comida 2",
        nombre: "Carne molida con verdura y aceite de oliva",
        subtotal: { kcal: 464, proteina: 46.0, cho: 22.0, grasa: 23.0 },
        alimentos: [
          { nombre: "Carne molida magra", cantidad: "180 g", kcal: 306, proteina: 36.0, cho: 0, grasa: 18.0, esLibre: false },
          { nombre: "Brócoli", cantidad: "200 g", kcal: 68, proteina: 6.0, cho: 13.0, grasa: 0, esLibre: false },
          { nombre: "Coliflor", cantidad: "180 g", kcal: 45, proteina: 4.0, cho: 9.0, grasa: 0, esLibre: false },
          { nombre: "Aceite oliva", cantidad: "5 g", kcal: 45, proteina: 0, cho: 0, grasa: 5.0, esLibre: false },
        ],
      },
      {
        numero: "Comida 3",
        nombre: "Huevos cocidos con fruta",
        subtotal: { kcal: 205, proteina: 13.5, cho: 16.0, grasa: 10.4 },
        alimentos: [
          { nombre: "Huevo entero cocido", cantidad: "2 unid (100 g)", kcal: 145, proteina: 13.0, cho: 1.0, grasa: 10.4, esLibre: false },
          { nombre: "Piña", cantidad: "120 g", kcal: 60, proteina: 0.5, cho: 15.0, grasa: 0, esLibre: false },
        ],
      },
      {
        numero: "Comida 4",
        nombre: "Pechuga de pollo con ensalada y aguacate",
        subtotal: { kcal: 391, proteina: 49.2, cho: 18.0, grasa: 14.0 },
        alimentos: [
          { nombre: "Pechuga pollo cruda", cantidad: "200 g", kcal: 240, proteina: 45.0, cho: 0, grasa: 5.0, esLibre: false },
          { nombre: "Lechuga", cantidad: "120 g", kcal: 18, proteina: 1.2, cho: 4.0, grasa: 0, esLibre: false },
          { nombre: "Pepino", cantidad: "120 g", kcal: 19, proteina: 0.8, cho: 5.0, grasa: 0, esLibre: false },
          { nombre: "Tomate", cantidad: "100 g", kcal: 18, proteina: 1.0, cho: 4.0, grasa: 0, esLibre: false },
          { nombre: "Aguacate", cantidad: "60 g", kcal: 96, proteina: 1.2, cho: 5.0, grasa: 9.0, esLibre: false },
        ],
      },
    ],
  },
  {
    id: 5,
    nombre: "Menú 4 - Bajos CHO",
    tag: "CHO Bajos",
    totales: { kcal: 1528, proteina: 113.0, cho: 164.3, grasa: 45.8 },
    comidas: [
      {
        numero: "Comida 1",
        nombre: "Pancakes de Avena con huevo",
        subtotal: { kcal: 341, proteina: 18.3, cho: 40.0, grasa: 12.4 },
        alimentos: [
          { nombre: "Huevo entero Doble A", cantidad: "2 huevos", kcal: 145, proteina: 13.0, cho: 1.0, grasa: 10.4, esLibre: false },
          { nombre: "Avena", cantidad: "30 g", kcal: 114, proteina: 4.0, cho: 20.0, grasa: 2.0, esLibre: false },
          { nombre: "Banano", cantidad: "50 g", kcal: 50, proteina: 0.6, cho: 12.0, grasa: 0, esLibre: false },
          { nombre: "Fresas", cantidad: "100 g", kcal: 32, proteina: 0.7, cho: 7.0, grasa: 0, esLibre: false },
        ],
      },
      {
        numero: "Comida 2",
        nombre: "Bowl de yogurt griego con fruta",
        subtotal: { kcal: 289, proteina: 13.4, cho: 31.8, grasa: 12.4 },
        alimentos: [
          { nombre: "Yogurt griego Dejamu", cantidad: "170 g", kcal: 168, proteina: 10.9, cho: 8.8, grasa: 10.0, esLibre: false },
          { nombre: "Arándanos", cantidad: "80 g", kcal: 45, proteina: 0.5, cho: 11.0, grasa: 0, esLibre: false },
          { nombre: "Mango", cantidad: "60 g", kcal: 36, proteina: 0.4, cho: 9.0, grasa: 0, esLibre: false },
          { nombre: "Chía", cantidad: "8 g", kcal: 40, proteina: 1.6, cho: 3.0, grasa: 2.4, esLibre: false },
        ],
      },
      {
        numero: "Comida 3",
        nombre: "Hamburgesa casera",
        subtotal: { kcal: 534, proteina: 38.9, cho: 55.5, grasa: 17.0 },
        alimentos: [
          { nombre: "Carne molida magra", cantidad: "150 g", kcal: 255, proteina: 30.0, cho: 0, grasa: 15.0, esLibre: false },
          { nombre: "Pan hamburguesa", cantidad: "60 g", kcal: 158, proteina: 6.0, cho: 28.0, grasa: 2.0, esLibre: false },
          { nombre: "Papa en air fryer", cantidad: "120 g", kcal: 104, proteina: 2.0, cho: 24.0, grasa: 0, esLibre: false },
          { nombre: "Lechuga", cantidad: "40 g", kcal: 6, proteina: 0.4, cho: 1.0, grasa: 0, esLibre: false },
          { nombre: "Tomate", cantidad: "60 g", kcal: 11, proteina: 0.5, cho: 2.5, grasa: 0, esLibre: false },
        ],
      },
      {
        numero: "Comida 4",
        nombre: "Pechuga de pollo con papa, Ahuyama y verduras",
        subtotal: { kcal: 364, proteina: 42.4, cho: 37.0, grasa: 4.0 },
        alimentos: [
          { nombre: "Pechuga pollo", cantidad: "170 g", kcal: 204, proteina: 39.0, cho: 0, grasa: 4.0, esLibre: false },
          { nombre: "Papa", cantidad: "80 g", kcal: 70, proteina: 1.6, cho: 16.0, grasa: 0, esLibre: false },
          { nombre: "Ahuyama", cantidad: "150 g", kcal: 53, proteina: 1.0, cho: 12.0, grasa: 0, esLibre: false },
          { nombre: "Zanahoria", cantidad: "60 g", kcal: 25, proteina: 0.5, cho: 6.0, grasa: 0, esLibre: false },
          { nombre: "Cebolla", cantidad: "30 g", kcal: 12, proteina: 0.3, cho: 3.0, grasa: 0, esLibre: false },
        ],
      },
    ],
  },
  {
    id: 6,
    nombre: "Menú 2 - Medios CHO",
    tag: "CHO Moderados",
    totales: { kcal: 1635, proteina: 123.2, cho: 171.8, grasa: 51.3 },
    comidas: [
      {
        numero: "Comida 1",
        nombre: "Wrap de Huevo y vegetales   con fruta",
        subtotal: { kcal: 378, proteina: 25.2, cho: 38.5, grasa: 14.4 },
        alimentos: [
          { nombre: "Pan integral", cantidad: "60 g", kcal: 150, proteina: 6.0, cho: 27.0, grasa: 2.0, esLibre: false },
          { nombre: "Huevo entero", cantidad: "100 g", kcal: 145, proteina: 13.0, cho: 1.0, grasa: 10.4, esLibre: false },
          { nombre: "Queso mozzarella light", cantidad: "20 g", kcal: 40, proteina: 5.0, cho: 1.0, grasa: 2.0, esLibre: false },
          { nombre: "Tomate", cantidad: "60 g", kcal: 11, proteina: 0.5, cho: 2.5, grasa: 0, esLibre: false },
          { nombre: "Fresas", cantidad: "100 g", kcal: 32, proteina: 0.7, cho: 7.0, grasa: 0, esLibre: false },
        ],
      },
      {
        numero: "Comida 2",
        nombre: "Pechuga de pollo con arroz y vegetales",
        subtotal: { kcal: 499, proteina: 48.5, cho: 56.0, grasa: 9.0 },
        alimentos: [
          { nombre: "Pechuga pollo cruda", cantidad: "170 g", kcal: 187, proteina: 39.0, cho: 0, grasa: 4.0, esLibre: false },
          { nombre: "Arroz blanco cocido", cantidad: "140 g", kcal: 182, proteina: 4.0, cho: 39.0, grasa: 0, esLibre: false },
          { nombre: "Brócoli", cantidad: "180 g", kcal: 60, proteina: 5.0, cho: 11.0, grasa: 0, esLibre: false },
          { nombre: "Zanahoria", cantidad: "60 g", kcal: 25, proteina: 0.5, cho: 6.0, grasa: 0, esLibre: false },
          { nombre: "Aceite oliva", cantidad: "5 g", kcal: 45, proteina: 0, cho: 0, grasa: 5.0, esLibre: false },
        ],
      },
      {
        numero: "Comida 3",
        nombre: "Bowl de Avena con fruta",
        subtotal: { kcal: 284, proteina: 13.6, cho: 30.8, grasa: 11.9 },
        alimentos: [
          { nombre: "Yogurt griego Dejamu", cantidad: "150 g", kcal: 149, proteina: 9.6, cho: 7.8, grasa: 8.9, esLibre: false },
          { nombre: "Arándanos", cantidad: "60 g", kcal: 34, proteina: 0.5, cho: 8.0, grasa: 0, esLibre: false },
          { nombre: "Avena", cantidad: "20 g", kcal: 76, proteina: 2.5, cho: 13.0, grasa: 1.5, esLibre: false },
          { nombre: "Chía", cantidad: "5 g", kcal: 25, proteina: 1.0, cho: 2.0, grasa: 1.5, esLibre: false },
        ],
      },
      {
        numero: "Comida 4",
        nombre: "Hamburguesa casera con papa en Air Fryer",
        subtotal: { kcal: 474, proteina: 35.9, cho: 46.5, grasa: 16.0 },
        alimentos: [
          { nombre: "Carne molida magra", cantidad: "140 g", kcal: 238, proteina: 28.0, cho: 0, grasa: 14.0, esLibre: false },
          { nombre: "Pan hamburguesa", cantidad: "50 g", kcal: 132, proteina: 5.0, cho: 23.0, grasa: 2.0, esLibre: false },
          { nombre: "Papa en air fryer", cantidad: "100 g", kcal: 87, proteina: 2.0, cho: 20.0, grasa: 0, esLibre: false },
          { nombre: "Lechuga", cantidad: "40 g", kcal: 6, proteina: 0.4, cho: 1.0, grasa: 0, esLibre: false },
          { nombre: "Tomate", cantidad: "60 g", kcal: 11, proteina: 0.5, cho: 2.5, grasa: 0, esLibre: false },
        ],
      },
    ],
  },
  {
    id: 7,
    nombre: "Menú 3 - Medios CHO",
    tag: "CHO Moderados",
    totales: { kcal: 1804, proteina: 148.6, cho: 188.3, grasa: 51.5 },
    comidas: [
      {
        numero: "Comida 1",
        nombre: "Arepas con huevo, aguacate y tomate",
        subtotal: { kcal: 412, proteina: 20.1, cho: 39.5, grasa: 20.5 },
        alimentos: [
          { nombre: "Arepa delgada", cantidad: "90 g", kcal: 147, proteina: 3.0, cho: 32.0, grasa: 1.0, esLibre: false },
          { nombre: "Huevo entero", cantidad: "120 g", kcal: 174, proteina: 15.6, cho: 1.0, grasa: 12.5, esLibre: false },
          { nombre: "Aguacate", cantidad: "50 g", kcal: 80, proteina: 1.0, cho: 4.0, grasa: 7.0, esLibre: false },
          { nombre: "Tomate", cantidad: "60 g", kcal: 11, proteina: 0.5, cho: 2.5, grasa: 0, esLibre: false },
        ],
      },
      {
        numero: "Comida 2",
        nombre: "Pasta con Lomo de cerdo y vegetales",
        subtotal: { kcal: 589, proteina: 50.5, cho: 61.0, grasa: 15.0 },
        alimentos: [
          { nombre: "Pasta cocida", cantidad: "160 g", kcal: 246, proteina: 8.0, cho: 50.0, grasa: 1.0, esLibre: false },
          { nombre: "Lomo de cerdo crudo", cantidad: "180 g", kcal: 254, proteina: 41.0, cho: 0, grasa: 9.0, esLibre: false },
          { nombre: "Pimentón", cantidad: "80 g", kcal: 24, proteina: 1.0, cho: 6.0, grasa: 0, esLibre: false },
          { nombre: "Cebolla", cantidad: "50 g", kcal: 20, proteina: 0.5, cho: 5.0, grasa: 0, esLibre: false },
          { nombre: "Aceite oliva", cantidad: "5 g", kcal: 45, proteina: 0, cho: 0, grasa: 5.0, esLibre: false },
        ],
      },
      {
        numero: "Comida 3",
        nombre: "Bowl de Yogurt griego con fruta y Whey protein",
        subtotal: { kcal: 354, proteina: 36.2, cho: 27.8, grasa: 12.0 },
        alimentos: [
          { nombre: "Yogurt griego Dejamu", cantidad: "170 g", kcal: 168, proteina: 10.9, cho: 8.8, grasa: 10.0, esLibre: false },
          { nombre: "Whey protein", cantidad: "30 g", kcal: 120, proteina: 24.0, cho: 3.0, grasa: 2.0, esLibre: false },
          { nombre: "Fresas", cantidad: "120 g", kcal: 38, proteina: 1.0, cho: 9.0, grasa: 0, esLibre: false },
          { nombre: "Arándanos", cantidad: "50 g", kcal: 28, proteina: 0.3, cho: 7.0, grasa: 0, esLibre: false },
        ],
      },
      {
        numero: "Comida 4",
        nombre: "Sopa espesa con pollo y papa",
        subtotal: { kcal: 449, proteina: 41.8, cho: 60.0, grasa: 4.0 },
        alimentos: [
          { nombre: "Pechuga pollo desmechada", cantidad: "160 g", kcal: 192, proteina: 37.0, cho: 0, grasa: 4.0, esLibre: false },
          { nombre: "Papa cocida", cantidad: "180 g", kcal: 156, proteina: 3.0, cho: 36.0, grasa: 0, esLibre: false },
          { nombre: "Ahuyama", cantidad: "180 g", kcal: 64, proteina: 1.0, cho: 15.0, grasa: 0, esLibre: false },
          { nombre: "Zanahoria", cantidad: "60 g", kcal: 25, proteina: 0.5, cho: 6.0, grasa: 0, esLibre: false },
          { nombre: "Cebolla", cantidad: "30 g", kcal: 12, proteina: 0.3, cho: 3.0, grasa: 0, esLibre: false },
        ],
      },
    ],
  },
  {
    id: 8,
    nombre: "Menú 5 - Bajos CHO",
    tag: "CHO Bajos",
    totales: { kcal: 1414, proteina: 132.9, cho: 138.3, grasa: 38.0 },
    comidas: [
      {
        numero: "Comida 1",
        nombre: "Huevos pericos con arepa y fruta",
        subtotal: { kcal: 307, proteina: 18.8, cho: 30.3, grasa: 13.0 },
        alimentos: [
          { nombre: "Huevo entero", cantidad: "120 g", kcal: 174, proteina: 15.6, cho: 1.0, grasa: 12.5, esLibre: false },
          { nombre: "Tomate", cantidad: "60 g", kcal: 11, proteina: 0.5, cho: 2.5, grasa: 0, esLibre: false },
          { nombre: "Cebolla larga", cantidad: "25 g", kcal: 8, proteina: 0.3, cho: 1.8, grasa: 0, esLibre: false },
          { nombre: "Arepa delgada", cantidad: "50 g", kcal: 82, proteina: 1.7, cho: 18.0, grasa: 0.5, esLibre: false },
          { nombre: "Fresas", cantidad: "100 g", kcal: 32, proteina: 0.7, cho: 7.0, grasa: 0, esLibre: false },
        ],
      },
      {
        numero: "Comida 2",
        nombre: "Carne asada con papa criolla y ensalada",
        subtotal: { kcal: 450, proteina: 42.0, cho: 35.0, grasa: 15.0 },
        alimentos: [
          { nombre: "Carne de res magra", cantidad: "170 g", kcal: 290, proteina: 38.0, cho: 0, grasa: 15.0, esLibre: false },
          { nombre: "Papa criolla cocida", cantidad: "120 g", kcal: 120, proteina: 2.0, cho: 26.0, grasa: 0, esLibre: false },
          { nombre: "Lechuga", cantidad: "60 g", kcal: 10, proteina: 0.7, cho: 2.0, grasa: 0, esLibre: false },
          { nombre: "Tomate", cantidad: "80 g", kcal: 14, proteina: 0.7, cho: 3.0, grasa: 0, esLibre: false },
          { nombre: "Pepino", cantidad: "100 g", kcal: 16, proteina: 0.6, cho: 4.0, grasa: 0, esLibre: false },
        ],
      },
      {
        numero: "Comida 3",
        nombre: "Whey Protein con fruta",
        subtotal: { kcal: 228, proteina: 25.3, cho: 30.0, grasa: 2.0 },
        alimentos: [
          { nombre: "Whey protein", cantidad: "30 g", kcal: 120, proteina: 24.0, cho: 3.0, grasa: 2.0, esLibre: false },
          { nombre: "Banano", cantidad: "80 g", kcal: 80, proteina: 1.0, cho: 20.0, grasa: 0, esLibre: false },
          { nombre: "Arándanos", cantidad: "50 g", kcal: 28, proteina: 0.3, cho: 7.0, grasa: 0, esLibre: false },
        ],
      },
      {
        numero: "Comida 2",
        nombre: "Higado encebollado de Res con ahuyama y brocolí",
        subtotal: { kcal: 429, proteina: 46.8, cho: 43.0, grasa: 8.0 },
        alimentos: [
          { nombre: "Hígado de res", cantidad: "200 g", kcal: 270, proteina: 40.0, cho: 8.0, grasa: 8.0, esLibre: false },
          { nombre: "Cebolla", cantidad: "60 g", kcal: 24, proteina: 0.6, cho: 6.0, grasa: 0, esLibre: false },
          { nombre: "Tomate", cantidad: "80 g", kcal: 14, proteina: 0.7, cho: 3.0, grasa: 0, esLibre: false },
          { nombre: "Ahuyama cocida", cantidad: "200 g", kcal: 71, proteina: 1.5, cho: 16.0, grasa: 0, esLibre: false },
          { nombre: "Brócoli", cantidad: "150 g", kcal: 50, proteina: 4.0, cho: 10.0, grasa: 0, esLibre: false },
        ],
      },
    ],
  },
  {
    id: 9,
    nombre: "Menú 4 - Moderados CHO",
    tag: "CHO Moderados",
    totales: { kcal: 1585, proteina: 118.7, cho: 172.5, grasa: 47.5 },
    comidas: [
      {
        numero: "Comida 1",
        nombre: "Huevos pericos con fruta y arepa",
        subtotal: { kcal: 395, proteina: 22.3, cho: 41.8, grasa: 16.0 },
        alimentos: [
          { nombre: "Huevo revuelto Doble A", cantidad: "150 g (3 huevos)", kcal: 218, proteina: 19.0, cho: 1.5, grasa: 15.5, esLibre: false },
          { nombre: "Tomate", cantidad: "60 g", kcal: 11, proteina: 0.5, cho: 2.5, grasa: 0, esLibre: false },
          { nombre: "Cebolla larga", cantidad: "25 g", kcal: 8, proteina: 0.3, cho: 1.8, grasa: 0, esLibre: false },
          { nombre: "Arepa delgada", cantidad: "60 g", kcal: 98, proteina: 2.0, cho: 21.0, grasa: 0.5, esLibre: false },
          { nombre: "Mango", cantidad: "100 g", kcal: 60, proteina: 0.5, cho: 15.0, grasa: 0, esLibre: false },
        ],
      },
      {
        numero: "Comida 2",
        nombre: "Lomo de cerdo con pasta y vegetales",
        subtotal: { kcal: 619, proteina: 51.7, cho: 67.0, grasa: 15.0 },
        alimentos: [
          { nombre: "Pasta cocida", cantidad: "170 g", kcal: 262, proteina: 8.5, cho: 53.0, grasa: 1.0, esLibre: false },
          { nombre: "Lomo de cerdo crudo", cantidad: "180 g", kcal: 254, proteina: 41.0, cho: 0, grasa: 9.0, esLibre: false },
          { nombre: "Pimentón", cantidad: "80 g", kcal: 24, proteina: 1.0, cho: 6.0, grasa: 0, esLibre: false },
          { nombre: "Cebolla", cantidad: "50 g", kcal: 20, proteina: 0.5, cho: 5.0, grasa: 0, esLibre: false },
          { nombre: "Tomate", cantidad: "80 g", kcal: 14, proteina: 0.7, cho: 3.0, grasa: 0, esLibre: false },
          { nombre: "Aceite oliva", cantidad: "5 g", kcal: 45, proteina: 0, cho: 0, grasa: 5.0, esLibre: false },
        ],
      },
      {
        numero: "Comida 3",
        nombre: "Pancakes de Proteina",
        subtotal: { kcal: 386, proteina: 35.7, cho: 41.5, grasa: 9.5 },
        alimentos: [
          { nombre: "Whey protein", cantidad: "30 g", kcal: 120, proteina: 24.0, cho: 3.0, grasa: 2.0, esLibre: false },
          { nombre: "Huevo entero", cantidad: "50 g", kcal: 73, proteina: 6.5, cho: 0.5, grasa: 5.0, esLibre: false },
          { nombre: "Avena", cantidad: "35 g", kcal: 133, proteina: 4.5, cho: 23.0, grasa: 2.5, esLibre: false },
          { nombre: "Banano", cantidad: "60 g", kcal: 60, proteina: 0.7, cho: 15.0, grasa: 0, esLibre: false },
        ],
      },
      {
        numero: "Comida 4",
        nombre: "Yogurt Griego con fruta",
        subtotal: { kcal: 185, proteina: 9.0, cho: 22.2, grasa: 7.0 },
        alimentos: [
          { nombre: "Yogurt griego Dejamu", cantidad: "120 g", kcal: 119, proteina: 7.7, cho: 6.2, grasa: 7.0, esLibre: false },
          { nombre: "Fresas", cantidad: "120 g", kcal: 38, proteina: 1.0, cho: 9.0, grasa: 0, esLibre: false },
          { nombre: "Arándanos", cantidad: "50 g", kcal: 28, proteina: 0.3, cho: 7.0, grasa: 0, esLibre: false },
        ],
      },
    ],
  },
  {
    id: 10,
    nombre: "Menú -  Altos CHO",
    tag: "CHO Altos",
    totales: { kcal: 1738, proteina: 85.6, cho: 118.5, grasa: 22.2 },
    comidas: [
      {
        numero: "Comida 2",
        nombre: "Bowl de arroz con pollo",
        subtotal: { kcal: 570, proteina: 48.6, cho: 67.0, grasa: 11.7 },
        alimentos: [
          { nombre: "Pechuga de pollo, cruda", cantidad: "180 g", kcal: 216, proteina: 39.6, cho: 0, grasa: 5.4, esLibre: false },
          { nombre: "Arroz blanco cocido", cantidad: "180 g", kcal: 232, proteina: 4.3, cho: 50.4, grasa: 0.5, esLibre: false },
          { nombre: "Brócoli cocinado", cantidad: "150 g", kcal: 51, proteina: 4.2, cho: 10.5, grasa: 0.6, esLibre: false },
          { nombre: "Zanahoria sin cáscara", cantidad: "80 g", kcal: 26, proteina: 0.5, cho: 6.1, grasa: 0.2, esLibre: false },
          { nombre: "Aceite de oliva", cantidad: "5 g", kcal: 45, proteina: 0, cho: 0, grasa: 5.0, esLibre: false },
        ],
      },
      {
        numero: "Comida 3",
        nombre: "Pancakes de Proteina",
        subtotal: { kcal: 443, proteina: 37.0, cho: 51.5, grasa: 10.5 },
        alimentos: [
          { nombre: "Whey protein", cantidad: "30 g", kcal: 120, proteina: 24.0, cho: 3.0, grasa: 2.0, esLibre: false },
          { nombre: "Avena", cantidad: "50 g", kcal: 190, proteina: 6.0, cho: 33.0, grasa: 3.5, esLibre: false },
          { nombre: "Huevo entero", cantidad: "50 g", kcal: 73, proteina: 6.5, cho: 0.5, grasa: 5.0, esLibre: false },
          { nombre: "Mango", cantidad: "100 g", kcal: 60, proteina: 0.5, cho: 15.0, grasa: 0, esLibre: false },
        ],
      },
      {
        numero: "Comida 4",
        nombre: "Comida libre - 650 a 800 kcal a elección",
        subtotal: { kcal: 725, proteina: 0, cho: 0, grasa: 0 },
        alimentos: [
          { nombre: "Comida libre — a tu elección", cantidad: "650 a 800 kcal", kcal: 725, proteina: 0, cho: 0, grasa: 0, esLibre: true },
        ],
      },
    ],
  },
  {
    id: 11,
    nombre: "Menú -  Bajos  CHO",
    tag: "CHO Bajos",
    totales: { kcal: 1582, proteina: 135.2, cho: 47.3, grasa: 153.7 },
    comidas: [
      {
        numero: "Comida 1",
        nombre: "Huevos revueltos con avena y fresas",
        subtotal: { kcal: 515, proteina: 22.1, cho: 16.9, grasa: 76.3 },
        alimentos: [
          { nombre: "Huevo de gallina revuelto", cantidad: "110", kcal: 167, proteina: 11.2, cho: 12.5, grasa: 2.5, esLibre: false },
          { nombre: "Avena hojuelas Quaker", cantidad: "45", kcal: 185, proteina: 7.6, cho: 3.4, grasa: 28.8, esLibre: false },
          { nombre: "Fresas crudas", cantidad: "130", kcal: 49, proteina: 1.0, cho: 0.4, grasa: 20.5, esLibre: false },
          { nombre: "Arepa de maíz con sal", cantidad: "70", kcal: 114, proteina: 2.3, cho: 0.6, grasa: 24.5, esLibre: false },
        ],
      },
      {
        numero: "Comida 2",
        nombre: "Pechuga de pollo",
        subtotal: { kcal: 430, proteina: 48.6, cho: 14.7, grasa: 22.5 },
        alimentos: [
          { nombre: "Pechuga de pollo asada", cantidad: "140", kcal: 230, proteina: 41.6, cho: 6.9, grasa: 0.3, esLibre: false },
          { nombre: "Brócoli cocido", cantidad: "150", kcal: 69, proteina: 4.5, cho: 0.5, grasa: 9.9, esLibre: false },
          { nombre: "Tomate crudo", cantidad: "100", kcal: 55, proteina: 2.0, cho: 0.2, grasa: 10.2, esLibre: false },
          { nombre: "Cebolla cabezona", cantidad: "40", kcal: 13, proteina: 0.5, cho: 0.1, grasa: 2.1, esLibre: false },
          { nombre: "Aceite de oliva", cantidad: "7", kcal: 63, proteina: 0, cho: 7.0, grasa: 0, esLibre: false },
        ],
      },
      {
        numero: "Comida 3",
        nombre: "Huevos revueltos con avena y fresas",
        subtotal: { kcal: 167, proteina: 12.8, cho: 4.3, grasa: 18.9 },
        alimentos: [
          { nombre: "Yogurt Griego Alpina", cantidad: "150", kcal: 116, proteina: 12.4, cho: 4.3, grasa: 6.8, esLibre: false },
          { nombre: "Uvas verdes", cantidad: "100", kcal: 51, proteina: 0.4, cho: 0, grasa: 12.1, esLibre: false },
        ],
      },
      {
        numero: "Comida 4",
        nombre: "Huevos revueltos con avena y fresas",
        subtotal: { kcal: 470, proteina: 51.7, cho: 11.4, grasa: 36.0 },
        alimentos: [
          { nombre: "Lomo de cerdo cocido", cantidad: "130", kcal: 221, proteina: 45.6, cho: 4.2, grasa: 0.3, esLibre: false },
          { nombre: "Papa sabanera cocida", cantidad: "100", kcal: 99, proteina: 2.3, cho: 0.1, grasa: 21.0, esLibre: false },
          { nombre: "Pimentón rojo", cantidad: "100", kcal: 35, proteina: 1.0, cho: 0.3, grasa: 6.3, esLibre: false },
          { nombre: "Espinaca cocida", cantidad: "80", kcal: 27, proteina: 2.3, cho: 0.2, grasa: 3.0, esLibre: false },
          { nombre: "Aguacate Hass", cantidad: "40", kcal: 88, proteina: 0.5, cho: 6.6, grasa: 5.4, esLibre: false },
        ],
      },
    ],
  },
  {
    id: 12,
    nombre: "Menú -  Bajos  CHO",
    tag: "CHO Bajos",
    totales: { kcal: 1612, proteina: 135.6, cho: 67.8, grasa: 98.2 },
    comidas: [
      {
        numero: "Comida 1",
        nombre: "Huevos revueltos con aguacate, tomate y aguacate",
        subtotal: { kcal: 491, proteina: 33.0, cho: 27.5, grasa: 23.9 },
        alimentos: [
          { nombre: "Huevo de gallina completo", cantidad: "150", kcal: 218, proteina: 19.5, cho: 15.6, grasa: 0, esLibre: false },
          { nombre: "Clara de huevo líquida", cantidad: "100", kcal: 42, proteina: 10.0, cho: 0, grasa: 0.5, esLibre: false },
          { nombre: "Aguacate Hass", cantidad: "70", kcal: 155, proteina: 0.9, cho: 11.5, grasa: 9.4, esLibre: false },
          { nombre: "Tomate crudo", cantidad: "100", kcal: 55, proteina: 2.0, cho: 0.2, grasa: 10.2, esLibre: false },
          { nombre: "Pimentón rojo", cantidad: "60", kcal: 21, proteina: 0.6, cho: 0.2, grasa: 3.8, esLibre: false },
        ],
      },
      {
        numero: "Comida 2",
        nombre: "Bowl de Atun con champiñones y verduras",
        subtotal: { kcal: 401, proteina: 39.2, cho: 12.8, grasa: 26.4 },
        alimentos: [
          { nombre: "Atún Isabel (enlatado)", cantidad: "120", kcal: 137, proteina: 30.0, cho: 1.7, grasa: 0, esLibre: false },
          { nombre: "Champiñones en conserva", cantidad: "120", kcal: 52, proteina: 2.3, cho: 0.5, grasa: 7.9, esLibre: false },
          { nombre: "Espinaca cocida", cantidad: "150", kcal: 51, proteina: 4.3, cho: 0.3, grasa: 5.7, esLibre: false },
          { nombre: "Tomate crudo", cantidad: "100", kcal: 55, proteina: 2.0, cho: 0.2, grasa: 10.2, esLibre: false },
          { nombre: "Cebolla cabezona", cantidad: "50", kcal: 16, proteina: 0.6, cho: 0.1, grasa: 2.6, esLibre: false },
          { nombre: "Aceite de oliva", cantidad: "10", kcal: 90, proteina: 0, cho: 10.0, grasa: 0, esLibre: false },
        ],
      },
      {
        numero: "Comida 3",
        nombre: "Yogurt Griego con Manzana",
        subtotal: { kcal: 197, proteina: 15.1, cho: 5.4, grasa: 21.3 },
        alimentos: [
          { nombre: "Yogurt Griego Alpina", cantidad: "180", kcal: 139, proteina: 14.9, cho: 5.2, grasa: 8.1, esLibre: false },
          { nombre: "Manzana verde", cantidad: "80", kcal: 58, proteina: 0.2, cho: 0.2, grasa: 13.2, esLibre: false },
        ],
      },
      {
        numero: "Comida 4",
        nombre: "Tilapia con champiñones, brocolí y aguacate",
        subtotal: { kcal: 523, proteina: 48.3, cho: 22.1, grasa: 26.6 },
        alimentos: [
          { nombre: "Tilapia cocida", cantidad: "200", kcal: 192, proteina: 40.2, cho: 3.4, grasa: 0, esLibre: false },
          { nombre: "Champiñones en conserva", cantidad: "100", kcal: 43, proteina: 1.9, cho: 0.4, grasa: 6.6, esLibre: false },
          { nombre: "Brócoli cocido", cantidad: "180", kcal: 83, proteina: 5.4, cho: 0.5, grasa: 11.9, esLibre: false },
          { nombre: "Aguacate Hass", cantidad: "60", kcal: 133, proteina: 0.8, cho: 9.8, grasa: 8.1, esLibre: false },
          { nombre: "Aceite de oliva", cantidad: "8", kcal: 72, proteina: 0, cho: 8.0, grasa: 0, esLibre: false },
        ],
      },
    ],
  },
  {
    id: 13,
    nombre: "Menú -  Bajos  CHO",
    tag: "CHO Bajos",
    totales: { kcal: 1585, proteina: 130.7, cho: 53.8, grasa: 137.9 },
    comidas: [
      {
        numero: "Comida 1",
        nombre: "Huevos revueltos con aguacate",
        subtotal: { kcal: 446, proteina: 22.4, cho: 20.9, grasa: 38.8 },
        alimentos: [
          { nombre: "Huevo de gallina completo", cantidad: "120", kcal: 174, proteina: 15.6, cho: 12.5, grasa: 0, esLibre: false },
          { nombre: "Pan integral", cantidad: "50", kcal: 140, proteina: 4.7, cho: 1.6, grasa: 25.2, esLibre: false },
          { nombre: "Aguacate Hass", cantidad: "40", kcal: 88, proteina: 0.5, cho: 6.6, grasa: 5.4, esLibre: false },
          { nombre: "Tomate crudo", cantidad: "80", kcal: 44, proteina: 1.6, cho: 0.2, grasa: 8.2, esLibre: false },
        ],
      },
      {
        numero: "Comida 2",
        nombre: "Lomo de cerdo con arroz y verdura",
        subtotal: { kcal: 496, proteina: 47.7, cho: 13.4, grasa: 42.5 },
        alimentos: [
          { nombre: "Lomo de cerdo cocido", cantidad: "120", kcal: 204, proteina: 42.1, cho: 3.8, grasa: 0.2, esLibre: false },
          { nombre: "Arroz blanco cocido", cantidad: "80", kcal: 129, proteina: 1.8, cho: 1.7, grasa: 26.0, esLibre: false },
          { nombre: "Champiñones en conserva", cantidad: "120", kcal: 52, proteina: 2.3, cho: 0.5, grasa: 7.9, esLibre: false },
          { nombre: "Pimentón rojo", cantidad: "100", kcal: 35, proteina: 1.0, cho: 0.3, grasa: 6.3, esLibre: false },
          { nombre: "Cebolla cabezona", cantidad: "40", kcal: 13, proteina: 0.5, cho: 0.1, grasa: 2.1, esLibre: false },
          { nombre: "Aceite de oliva", cantidad: "7", kcal: 63, proteina: 0, cho: 7.0, grasa: 0, esLibre: false },
        ],
      },
      {
        numero: "Comida 3",
        nombre: "Yougrt Griego con fruta",
        subtotal: { kcal: 225, proteina: 11.8, cho: 10.3, grasa: 25.7 },
        alimentos: [
          { nombre: "Yogurt Griego Dejamu", cantidad: "170", kcal: 168, proteina: 10.9, cho: 10.0, grasa: 8.8, esLibre: false },
          { nombre: "Piña cruda", cantidad: "60", kcal: 34, proteina: 0.4, cho: 0.1, grasa: 7.4, esLibre: false },
          { nombre: "Fresas crudas", cantidad: "60", kcal: 23, proteina: 0.5, cho: 0.2, grasa: 9.5, esLibre: false },
        ],
      },
      {
        numero: "Comida 4",
        nombre: "Camarones con papa y verdura",
        subtotal: { kcal: 418, proteina: 48.8, cho: 9.2, grasa: 30.9 },
        alimentos: [
          { nombre: "Camarón cocido", cantidad: "180", kcal: 185, proteina: 42.3, cho: 1.8, grasa: 0, esLibre: false },
          { nombre: "Papa criolla cocida", cantidad: "100", kcal: 85, proteina: 1.4, cho: 0, grasa: 18.1, esLibre: false },
          { nombre: "Espinaca cocida", cantidad: "120", kcal: 41, proteina: 3.5, cho: 0.2, grasa: 4.6, esLibre: false },
          { nombre: "Tomate crudo", cantidad: "80", kcal: 44, proteina: 1.6, cho: 0.2, grasa: 8.2, esLibre: false },
          { nombre: "Aceite de oliva", cantidad: "7", kcal: 63, proteina: 0, cho: 7.0, grasa: 0, esLibre: false },
        ],
      },
    ],
  },
  {
    id: 14,
    nombre: "Menú -  Bajos  CHO",
    tag: "CHO Bajos",
    totales: { kcal: 1775, proteina: 124.7, cho: 67.4, grasa: 163.4 },
    comidas: [
      {
        numero: "Comida 1",
        nombre: "Huevos revueltos con avena y fresas",
        subtotal: { kcal: 471, proteina: 25.0, cho: 21.7, grasa: 51.0 },
        alimentos: [
          { nombre: "Avena hojuelas Quaker", cantidad: "50", kcal: 206, proteina: 8.4, cho: 3.8, grasa: 32.0, esLibre: false },
          { nombre: "Huevo de gallina completo", cantidad: "120", kcal: 174, proteina: 15.6, cho: 12.5, grasa: 0, esLibre: false },
          { nombre: "Fresas crudas", cantidad: "120", kcal: 46, proteina: 1.0, cho: 0.4, grasa: 19.0, esLibre: false },
          { nombre: "Aceite de oliva", cantidad: "5", kcal: 45, proteina: 0, cho: 5.0, grasa: 0, esLibre: false },
        ],
      },
      {
        numero: "Comida 2",
        nombre: "Pechuga de pollo con pasta y champiñones",
        subtotal: { kcal: 556, proteina: 49.9, cho: 15.2, grasa: 50.7 },
        alimentos: [
          { nombre: "Pechuga de pollo asada", cantidad: "130", kcal: 213, proteina: 38.6, cho: 6.4, grasa: 0.3, esLibre: false },
          { nombre: "Pasta cocida (espagueti)", cantidad: "110", kcal: 157, proteina: 6.4, cho: 1.0, grasa: 29.7, esLibre: false },
          { nombre: "Champiñones en conserva", cantidad: "120", kcal: 52, proteina: 2.3, cho: 0.5, grasa: 7.9, esLibre: false },
          { nombre: "Tomate crudo", cantidad: "100", kcal: 55, proteina: 2.0, cho: 0.2, grasa: 10.2, esLibre: false },
          { nombre: "Cebolla cabezona", cantidad: "50", kcal: 16, proteina: 0.6, cho: 0.1, grasa: 2.6, esLibre: false },
          { nombre: "Aceite de oliva", cantidad: "7", kcal: 63, proteina: 0, cho: 7.0, grasa: 0, esLibre: false },
        ],
      },
      {
        numero: "Comida 3",
        nombre: "Yogurt Griego con fruta",
        subtotal: { kcal: 231, proteina: 11.4, cho: 10.0, grasa: 22.5 },
        alimentos: [
          { nombre: "Yogurt Griego Dejamu", cantidad: "170", kcal: 168, proteina: 10.9, cho: 10.0, grasa: 8.8, esLibre: false },
          { nombre: "Mango", cantidad: "80", kcal: 63, proteina: 0.5, cho: 0, grasa: 13.7, esLibre: false },
        ],
      },
      {
        numero: "Comida 4",
        nombre: "Salmón con papa, brocolí y verduras",
        subtotal: { kcal: 517, proteina: 38.4, cho: 20.5, grasa: 39.2 },
        alimentos: [
          { nombre: "Salmón filete cocido", cantidad: "130", kcal: 235, proteina: 26.3, cho: 14.3, grasa: 0.4, esLibre: false },
          { nombre: "Papa sabanera cocida", cantidad: "70", kcal: 69, proteina: 1.6, cho: 0.1, grasa: 14.7, esLibre: false },
          { nombre: "Brócoli cocido", cantidad: "200", kcal: 92, proteina: 6.0, cho: 0.6, grasa: 13.2, esLibre: false },
          { nombre: "Pimentón rojo", cantidad: "100", kcal: 35, proteina: 1.0, cho: 0.3, grasa: 6.3, esLibre: false },
          { nombre: "Espinaca cocida", cantidad: "120", kcal: 41, proteina: 3.5, cho: 0.2, grasa: 4.6, esLibre: false },
          { nombre: "Aceite de oliva", cantidad: "5", kcal: 45, proteina: 0, cho: 5.0, grasa: 0, esLibre: false },
        ],
      },
    ],
  },
  {
    id: 15,
    nombre: "Menú -  Moderados  CHO",
    tag: "CHO Moderados",
    totales: { kcal: 1750, proteina: 146.9, cho: 62.2, grasa: 135.2 },
    comidas: [
      {
        numero: "Comida 1",
        nombre: "Huevos revueltos con arepa aguacate y champiñon",
        subtotal: { kcal: 522, proteina: 25.8, cho: 25.0, grasa: 44.4 },
        alimentos: [
          { nombre: "Huevo de gallina completo", cantidad: "150", kcal: 218, proteina: 19.5, cho: 15.6, grasa: 0, esLibre: false },
          { nombre: "Arepa de maíz con sal", cantidad: "65", kcal: 106, proteina: 2.1, cho: 0.6, grasa: 22.8, esLibre: false },
          { nombre: "Aguacate Hass", cantidad: "50", kcal: 111, proteina: 0.7, cho: 8.2, grasa: 6.8, esLibre: false },
          { nombre: "Champiñones en conserva", cantidad: "100", kcal: 43, proteina: 1.9, cho: 0.4, grasa: 6.6, esLibre: false },
          { nombre: "Tomate crudo", cantidad: "80", kcal: 44, proteina: 1.6, cho: 0.2, grasa: 8.2, esLibre: false },
        ],
      },
      {
        numero: "Comida 2",
        nombre: "Arroz blanco con Salmón y verdura",
        subtotal: { kcal: 522, proteina: 35.8, cho: 23.6, grasa: 37.8 },
        alimentos: [
          { nombre: "Salmón filete cocido", cantidad: "140", kcal: 253, proteina: 28.3, cho: 15.4, grasa: 0.4, esLibre: false },
          { nombre: "Arroz blanco cocido", cantidad: "70", kcal: 113, proteina: 1.6, cho: 1.5, grasa: 22.8, esLibre: false },
          { nombre: "Espinaca cocida", cantidad: "150", kcal: 51, proteina: 4.3, cho: 0.3, grasa: 5.7, esLibre: false },
          { nombre: "Pimentón rojo", cantidad: "100", kcal: 35, proteina: 1.0, cho: 0.3, grasa: 6.3, esLibre: false },
          { nombre: "Cebolla cabezona", cantidad: "50", kcal: 16, proteina: 0.6, cho: 0.1, grasa: 2.6, esLibre: false },
          { nombre: "Aceite de oliva", cantidad: "6", kcal: 54, proteina: 0, cho: 6.0, grasa: 0, esLibre: false },
        ],
      },
      {
        numero: "Comida 3",
        nombre: "Atún enlatado con manzana",
        subtotal: { kcal: 189, proteina: 22.4, cho: 0.5, grasa: 21.4 },
        alimentos: [
          { nombre: "Atún Vikingos (enlatado)", cantidad: "100", kcal: 95, proteina: 22.0, cho: 0.2, grasa: 0, esLibre: false },
          { nombre: "Manzana verde", cantidad: "130", kcal: 94, proteina: 0.4, cho: 0.3, grasa: 21.4, esLibre: false },
        ],
      },
      {
        numero: "Comida 4",
        nombre: "Lomo de cerdo con brocolí y verdura",
        subtotal: { kcal: 517, proteina: 62.9, cho: 13.1, grasa: 31.6 },
        alimentos: [
          { nombre: "Lomo de cerdo cocido", cantidad: "150", kcal: 255, proteina: 52.6, cho: 4.8, grasa: 0.3, esLibre: false },
          { nombre: "Brócoli cocido", cantidad: "200", kcal: 92, proteina: 6.0, cho: 0.6, grasa: 13.2, esLibre: false },
          { nombre: "Champiñones en conserva", cantidad: "120", kcal: 52, proteina: 2.3, cho: 0.5, grasa: 7.9, esLibre: false },
          { nombre: "Tomate crudo", cantidad: "100", kcal: 55, proteina: 2.0, cho: 0.2, grasa: 10.2, esLibre: false },
          { nombre: "Aceite de oliva", cantidad: "7", kcal: 63, proteina: 0, cho: 7.0, grasa: 0, esLibre: false },
        ],
      },
    ],
  },
  {
    id: 16,
    nombre: "Menú -  Moderados  CHO",
    tag: "CHO Moderados",
    totales: { kcal: 1785, proteina: 144.1, cho: 60.7, grasa: 149.9 },
    comidas: [
      {
        numero: "Comida 1",
        nombre: "Huevos revueltos con avena y fruta",
        subtotal: { kcal: 500, proteina: 23.8, cho: 23.3, grasa: 44.1 },
        alimentos: [
          { nombre: "Avena hojuelas Quaker", cantidad: "45", kcal: 185, proteina: 7.6, cho: 3.4, grasa: 28.8, esLibre: false },
          { nombre: "Huevo de gallina completo", cantidad: "100", kcal: 145, proteina: 13.0, cho: 10.4, grasa: 0, esLibre: false },
          { nombre: "Mora / arándanos", cantidad: "100", kcal: 74, proteina: 1.0, cho: 0.1, grasa: 14.6, esLibre: false },
          { nombre: "Nueces", cantidad: "15", kcal: 96, proteina: 2.2, cho: 9.4, grasa: 0.7, esLibre: false },
        ],
      },
      {
        numero: "Comida 2",
        nombre: "Pasta con camarones, champiñones y verdura",
        subtotal: { kcal: 525, proteina: 54.9, cho: 10.8, grasa: 47.0 },
        alimentos: [
          { nombre: "Camarón cocido", cantidad: "180", kcal: 185, proteina: 42.3, cho: 1.8, grasa: 0, esLibre: false },
          { nombre: "Pasta cocida (espagueti)", cantidad: "100", kcal: 143, proteina: 5.8, cho: 0.9, grasa: 27.0, esLibre: false },
          { nombre: "Champiñones en conserva", cantidad: "150", kcal: 65, proteina: 2.9, cho: 0.6, grasa: 9.9, esLibre: false },
          { nombre: "Pimentón rojo", cantidad: "100", kcal: 35, proteina: 1.0, cho: 0.3, grasa: 6.3, esLibre: false },
          { nombre: "Espinaca cocida", cantidad: "100", kcal: 34, proteina: 2.9, cho: 0.2, grasa: 3.8, esLibre: false },
          { nombre: "Aceite de oliva", cantidad: "7", kcal: 63, proteina: 0, cho: 7.0, grasa: 0, esLibre: false },
        ],
      },
      {
        numero: "Comida 3",
        nombre: "Queso con uvas",
        subtotal: { kcal: 244, proteina: 14.2, cho: 12.8, grasa: 17.6 },
        alimentos: [
          { nombre: "Queso mozzarella", cantidad: "60", kcal: 178, proteina: 13.7, cho: 12.8, grasa: 1.9, esLibre: false },
          { nombre: "Uvas verdes", cantidad: "130", kcal: 66, proteina: 0.5, cho: 0, grasa: 15.7, esLibre: false },
        ],
      },
      {
        numero: "Comida 4",
        nombre: "Pechuga de pollo con papa y verduras",
        subtotal: { kcal: 516, proteina: 51.2, cho: 13.8, grasa: 41.2 },
        alimentos: [
          { nombre: "Pechuga de pollo asada", cantidad: "140", kcal: 230, proteina: 41.6, cho: 6.9, grasa: 0.3, esLibre: false },
          { nombre: "Papa criolla cocida", cantidad: "90", kcal: 77, proteina: 1.3, cho: 0, grasa: 16.3, esLibre: false },
          { nombre: "Brócoli cocido", cantidad: "200", kcal: 92, proteina: 6.0, cho: 0.6, grasa: 13.2, esLibre: false },
          { nombre: "Cebolla cabezona", cantidad: "60", kcal: 19, proteina: 0.7, cho: 0.1, grasa: 3.2, esLibre: false },
          { nombre: "Tomate crudo", cantidad: "80", kcal: 44, proteina: 1.6, cho: 0.2, grasa: 8.2, esLibre: false },
          { nombre: "Aceite de oliva", cantidad: "6", kcal: 54, proteina: 0, cho: 6.0, grasa: 0, esLibre: false },
        ],
      },
    ],
  },
  {
    id: 17,
    nombre: "Menú -  Moderados  CHO",
    tag: "CHO Moderados",
    totales: { kcal: 1677, proteina: 123.0, cho: 60.4, grasa: 156.8 },
    comidas: [
      {
        numero: "Comida 1",
        nombre: "Huevos revueltos con pan, aguacate y verdura",
        subtotal: { kcal: 523, proteina: 26.9, cho: 24.9, grasa: 43.3 },
        alimentos: [
          { nombre: "Huevo de gallina completo", cantidad: "150", kcal: 218, proteina: 19.5, cho: 15.6, grasa: 0, esLibre: false },
          { nombre: "Pan integral", cantidad: "45", kcal: 126, proteina: 4.2, cho: 1.4, grasa: 22.7, esLibre: false },
          { nombre: "Aguacate Hass", cantidad: "45", kcal: 100, proteina: 0.6, cho: 7.4, grasa: 6.1, esLibre: false },
          { nombre: "Pimentón rojo", cantidad: "100", kcal: 35, proteina: 1.0, cho: 0.3, grasa: 6.3, esLibre: false },
          { nombre: "Tomate crudo", cantidad: "80", kcal: 44, proteina: 1.6, cho: 0.2, grasa: 8.2, esLibre: false },
        ],
      },
      {
        numero: "Comida 2",
        nombre: "Tilapia con papa sabanera, champiñones y verdura",
        subtotal: { kcal: 475, proteina: 49.8, cho: 12.5, grasa: 35.0 },
        alimentos: [
          { nombre: "Tilapia cocida", cantidad: "200", kcal: 192, proteina: 40.2, cho: 3.4, grasa: 0, esLibre: false },
          { nombre: "Papa sabanera cocida", cantidad: "80", kcal: 79, proteina: 1.8, cho: 0.1, grasa: 16.8, esLibre: false },
          { nombre: "Champiñones en conserva", cantidad: "150", kcal: 65, proteina: 2.9, cho: 0.6, grasa: 9.9, esLibre: false },
          { nombre: "Espinaca cocida", cantidad: "150", kcal: 51, proteina: 4.3, cho: 0.3, grasa: 5.7, esLibre: false },
          { nombre: "Cebolla cabezona", cantidad: "50", kcal: 16, proteina: 0.6, cho: 0.1, grasa: 2.6, esLibre: false },
          { nombre: "Aceite de oliva", cantidad: "8", kcal: 72, proteina: 0, cho: 8.0, grasa: 0, esLibre: false },
        ],
      },
      {
        numero: "Comida 3",
        nombre: "Frutos secos con fruta",
        subtotal: { kcal: 208, proteina: 3.9, cho: 12.8, grasa: 31.0 },
        alimentos: [
          { nombre: "Almendras", cantidad: "20", kcal: 117, proteina: 2.4, cho: 12.3, grasa: 2.1, esLibre: false },
          { nombre: "Fresas crudas", cantidad: "120", kcal: 46, proteina: 1.0, cho: 0.4, grasa: 19.0, esLibre: false },
          { nombre: "Piña cruda", cantidad: "80", kcal: 45, proteina: 0.5, cho: 0.1, grasa: 9.9, esLibre: false },
        ],
      },
      {
        numero: "Comida 4",
        nombre: "Arroz con atún y verdura",
        subtotal: { kcal: 471, proteina: 42.4, cho: 10.2, grasa: 47.5 },
        alimentos: [
          { nombre: "Atún Isabel (enlatado)", cantidad: "130", kcal: 148, proteina: 32.5, cho: 1.8, grasa: 0, esLibre: false },
          { nombre: "Arroz blanco cocido", cantidad: "65", kcal: 105, proteina: 1.5, cho: 1.4, grasa: 21.1, esLibre: false },
          { nombre: "Brócoli cocido", cantidad: "200", kcal: 92, proteina: 6.0, cho: 0.6, grasa: 13.2, esLibre: false },
          { nombre: "Pimentón rojo", cantidad: "80", kcal: 28, proteina: 0.8, cho: 0.2, grasa: 5.0, esLibre: false },
          { nombre: "Tomate crudo", cantidad: "80", kcal: 44, proteina: 1.6, cho: 0.2, grasa: 8.2, esLibre: false },
          { nombre: "Aceite de oliva", cantidad: "6", kcal: 54, proteina: 0, cho: 6.0, grasa: 0, esLibre: false },
        ],
      },
    ],
  },
  {
    id: 18,
    nombre: "Menú -  Moderados  CHO",
    tag: "CHO Moderados",
    totales: { kcal: 1755, proteina: 148.7, cho: 58.8, grasa: 149.8 },
    comidas: [
      {
        numero: "Comida 1",
        nombre: "Huevos revueltos con champiñon y brocolí",
        subtotal: { kcal: 475, proteina: 27.9, cho: 22.0, grasa: 37.4 },
        alimentos: [
          { nombre: "Huevo de gallina completo", cantidad: "150", kcal: 218, proteina: 19.5, cho: 15.6, grasa: 0, esLibre: false },
          { nombre: "Champiñones en conserva", cantidad: "120", kcal: 52, proteina: 2.3, cho: 0.5, grasa: 7.9, esLibre: false },
          { nombre: "Espinaca cocida", cantidad: "100", kcal: 34, proteina: 2.9, cho: 0.2, grasa: 3.8, esLibre: false },
          { nombre: "Arepa de maíz con sal", cantidad: "50", kcal: 82, proteina: 1.6, cho: 0.5, grasa: 17.5, esLibre: false },
          { nombre: "Tomate crudo", cantidad: "80", kcal: 44, proteina: 1.6, cho: 0.2, grasa: 8.2, esLibre: false },
          { nombre: "Aceite de oliva", cantidad: "5", kcal: 45, proteina: 0, cho: 5.0, grasa: 0, esLibre: false },
        ],
      },
      {
        numero: "Comida 2",
        nombre: "Lomo de cerdo con pasta y verdura",
        subtotal: { kcal: 540, proteina: 55.4, cho: 12.7, grasa: 47.8 },
        alimentos: [
          { nombre: "Lomo de cerdo cocido", cantidad: "130", kcal: 221, proteina: 45.6, cho: 4.2, grasa: 0.3, esLibre: false },
          { nombre: "Pasta cocida (espagueti)", cantidad: "110", kcal: 157, proteina: 6.4, cho: 1.0, grasa: 29.7, esLibre: false },
          { nombre: "Tomate crudo", cantidad: "100", kcal: 55, proteina: 2.0, cho: 0.2, grasa: 10.2, esLibre: false },
          { nombre: "Cebolla cabezona", cantidad: "50", kcal: 16, proteina: 0.6, cho: 0.1, grasa: 2.6, esLibre: false },
          { nombre: "Pimentón rojo", cantidad: "80", kcal: 28, proteina: 0.8, cho: 0.2, grasa: 5.0, esLibre: false },
          { nombre: "Aceite de oliva", cantidad: "7", kcal: 63, proteina: 0, cho: 7.0, grasa: 0, esLibre: false },
        ],
      },
      {
        numero: "Comida 3",
        nombre: "Yogurt Griego con fruta",
        subtotal: { kcal: 226, proteina: 11.2, cho: 9.7, grasa: 27.7 },
        alimentos: [
          { nombre: "Yogurt Griego Dejamu", cantidad: "160", kcal: 158, proteina: 10.2, cho: 9.4, grasa: 8.3, esLibre: false },
          { nombre: "Piña cruda", cantidad: "80", kcal: 45, proteina: 0.5, cho: 0.1, grasa: 9.9, esLibre: false },
          { nombre: "Fresas crudas", cantidad: "60", kcal: 23, proteina: 0.5, cho: 0.2, grasa: 9.5, esLibre: false },
        ],
      },
      {
        numero: "Comida 4",
        nombre: "Pechuga de pollo con papa, brocolí y champiñon",
        subtotal: { kcal: 514, proteina: 54.2, cho: 14.4, grasa: 36.9 },
        alimentos: [
          { nombre: "Pechuga de pollo asada", cantidad: "150", kcal: 246, proteina: 44.5, cho: 7.3, grasa: 0.3, esLibre: false },
          { nombre: "Papa sabanera cocida", cantidad: "80", kcal: 79, proteina: 1.8, cho: 0.1, grasa: 16.8, esLibre: false },
          { nombre: "Brócoli cocido", cantidad: "200", kcal: 92, proteina: 6.0, cho: 0.6, grasa: 13.2, esLibre: false },
          { nombre: "Champiñones en conserva", cantidad: "100", kcal: 43, proteina: 1.9, cho: 0.4, grasa: 6.6, esLibre: false },
          { nombre: "Aceite de oliva", cantidad: "6", kcal: 54, proteina: 0, cho: 6.0, grasa: 0, esLibre: false },
        ],
      },
    ],
  },
  {
    id: 19,
    nombre: "Menú -  Altos  CHO",
    tag: "CHO Altos",
    totales: { kcal: 2173, proteina: 99.1, cho: 63.2, grasa: 121.8 },
    comidas: [
      {
        numero: "Comida 1",
        nombre: "Huevos revueltos con avena y frutos secos",
        subtotal: { kcal: 637, proteina: 30.1, cho: 35.5, grasa: 56.7 },
        alimentos: [
          { nombre: "Avena hojuelas Quaker", cantidad: "55", kcal: 226, proteina: 9.3, cho: 4.1, grasa: 35.3, esLibre: false },
          { nombre: "Huevo de gallina completo", cantidad: "130", kcal: 189, proteina: 16.9, cho: 13.5, grasa: 0, esLibre: false },
          { nombre: "Fresas crudas", cantidad: "130", kcal: 49, proteina: 1.0, cho: 0.4, grasa: 20.5, esLibre: false },
          { nombre: "Nueces", cantidad: "20", kcal: 128, proteina: 2.9, cho: 12.5, grasa: 0.9, esLibre: false },
          { nombre: "Aceite de oliva", cantidad: "5", kcal: 45, proteina: 0, cho: 5.0, grasa: 0, esLibre: false },
        ],
      },
      {
        numero: "Comida 2",
        nombre: "Comida libre",
        subtotal: { kcal: 725, proteina: 0, cho: 0, grasa: 0 },
        alimentos: [
          { nombre: "Comida libre — a tu elección", cantidad: "650 a 800 kcal", kcal: 725, proteina: 0, cho: 0, grasa: 0, esLibre: true },
        ],
      },
      {
        numero: "Comida 3",
        nombre: "Atun enlatado con manzana",
        subtotal: { kcal: 200, proteina: 25.4, cho: 1.6, grasa: 19.8 },
        alimentos: [
          { nombre: "Atún Isabel (enlatado)", cantidad: "100", kcal: 114, proteina: 25.0, cho: 1.4, grasa: 0, esLibre: false },
          { nombre: "Manzana verde", cantidad: "120", kcal: 86, proteina: 0.4, cho: 0.2, grasa: 19.8, esLibre: false },
        ],
      },
      {
        numero: "Comida 4",
        nombre: "Filete de salmón con arroz y brocolí",
        subtotal: { kcal: 611, proteina: 43.6, cho: 26.1, grasa: 45.3 },
        alimentos: [
          { nombre: "Salmón filete cocido", cantidad: "160", kcal: 290, proteina: 32.3, cho: 17.6, grasa: 0.5, esLibre: false },
          { nombre: "Arroz blanco cocido", cantidad: "70", kcal: 113, proteina: 1.6, cho: 1.5, grasa: 22.8, esLibre: false },
          { nombre: "Brócoli cocido", cantidad: "200", kcal: 92, proteina: 6.0, cho: 0.6, grasa: 13.2, esLibre: false },
          { nombre: "Espinaca cocida", cantidad: "100", kcal: 34, proteina: 2.9, cho: 0.2, grasa: 3.8, esLibre: false },
          { nombre: "Pimentón rojo", cantidad: "80", kcal: 28, proteina: 0.8, cho: 0.2, grasa: 5.0, esLibre: false },
          { nombre: "Aceite de oliva", cantidad: "6", kcal: 54, proteina: 0, cho: 6.0, grasa: 0, esLibre: false },
        ],
      },
    ],
  },
  {
    id: 20,
    nombre: "Menú -  Altos  CHO",
    tag: "CHO Altos",
    totales: { kcal: 2158, proteina: 97.8, cho: 60.1, grasa: 114.2 },
    comidas: [
      {
        numero: "Comida 1",
        nombre: "Huevos con champiñones, aguacate y pan integral",
        subtotal: { kcal: 544, proteina: 27.9, cho: 25.7, grasa: 45.0 },
        alimentos: [
          { nombre: "Huevo de gallina completo", cantidad: "150", kcal: 218, proteina: 19.5, cho: 15.6, grasa: 0, esLibre: false },
          { nombre: "Pan integral", cantidad: "45", kcal: 126, proteina: 4.2, cho: 1.4, grasa: 22.7, esLibre: false },
          { nombre: "Aguacate Hass", cantidad: "50", kcal: 111, proteina: 0.7, cho: 8.2, grasa: 6.8, esLibre: false },
          { nombre: "Tomate crudo", cantidad: "100", kcal: 55, proteina: 2.0, cho: 0.2, grasa: 10.2, esLibre: false },
          { nombre: "Champiñones en conserva", cantidad: "80", kcal: 34, proteina: 1.5, cho: 0.3, grasa: 5.3, esLibre: false },
        ],
      },
      {
        numero: "Comida 2",
        nombre: "Pechuga de pollo con pasta y champiñones",
        subtotal: { kcal: 593, proteina: 57.7, cho: 16.3, grasa: 48.1 },
        alimentos: [
          { nombre: "Pechuga de pollo asada", cantidad: "150", kcal: 246, proteina: 44.5, cho: 7.3, grasa: 0.3, esLibre: false },
          { nombre: "Pasta cocida (espagueti)", cantidad: "100", kcal: 143, proteina: 5.8, cho: 0.9, grasa: 27.0, esLibre: false },
          { nombre: "Champiñones en conserva", cantidad: "150", kcal: 65, proteina: 2.9, cho: 0.6, grasa: 9.9, esLibre: false },
          { nombre: "Pimentón rojo", cantidad: "100", kcal: 35, proteina: 1.0, cho: 0.3, grasa: 6.3, esLibre: false },
          { nombre: "Espinaca cocida", cantidad: "120", kcal: 41, proteina: 3.5, cho: 0.2, grasa: 4.6, esLibre: false },
          { nombre: "Aceite de oliva", cantidad: "7", kcal: 63, proteina: 0, cho: 7.0, grasa: 0, esLibre: false },
        ],
      },
      {
        numero: "Comida 3",
        nombre: "Yogurt griego con fruta y frutos secos",
        subtotal: { kcal: 296, proteina: 12.2, cho: 18.1, grasa: 21.1 },
        alimentos: [
          { nombre: "Yogurt Griego Dejamu", cantidad: "150", kcal: 149, proteina: 9.6, cho: 8.8, grasa: 7.8, esLibre: false },
          { nombre: "Mora / arándanos", cantidad: "80", kcal: 59, proteina: 0.8, cho: 0.1, grasa: 11.7, esLibre: false },
          { nombre: "Almendras", cantidad: "15", kcal: 88, proteina: 1.8, cho: 9.2, grasa: 1.6, esLibre: false },
        ],
      },
      {
        numero: "Comida 4",
        nombre: "Comida libre",
        subtotal: { kcal: 725, proteina: 0, cho: 0, grasa: 0 },
        alimentos: [
          { nombre: "Comida libre — a tu elección", cantidad: "650 a 800 kcal", kcal: 725, proteina: 0, cho: 0, grasa: 0, esLibre: true },
        ],
      },
    ],
  },
  {
    id: 21,
    nombre: "Menú -  Altos  CHO",
    tag: "CHO Altos",
    totales: { kcal: 2123, proteina: 109.6, cho: 51.8, grasa: 112.0 },
    comidas: [
      {
        numero: "Comida 1",
        nombre: "Huevos revueltos con arepa, aguacate y champiñones",
        subtotal: { kcal: 566, proteina: 27.7, cho: 26.8, grasa: 48.7 },
        alimentos: [
          { nombre: "Huevo de gallina completo", cantidad: "160", kcal: 232, proteina: 20.8, cho: 16.6, grasa: 0, esLibre: false },
          { nombre: "Arepa de maíz con sal", cantidad: "70", kcal: 114, proteina: 2.3, cho: 0.6, grasa: 24.5, esLibre: false },
          { nombre: "Aguacate Hass", cantidad: "55", kcal: 122, proteina: 0.7, cho: 9.0, grasa: 7.4, esLibre: false },
          { nombre: "Champiñones en conserva", cantidad: "100", kcal: 43, proteina: 1.9, cho: 0.4, grasa: 6.6, esLibre: false },
          { nombre: "Tomate crudo", cantidad: "100", kcal: 55, proteina: 2.0, cho: 0.2, grasa: 10.2, esLibre: false },
        ],
      },
      {
        numero: "Comida 2",
        nombre: "Comida libre",
        subtotal: { kcal: 725, proteina: 0, cho: 0, grasa: 0 },
        alimentos: [
          { nombre: "Comida libre — a tu elección", cantidad: "650 a 800 kcal", kcal: 725, proteina: 0, cho: 0, grasa: 0, esLibre: true },
        ],
      },
      {
        numero: "Comida 3",
        nombre: "Queso mozarella con fruta",
        subtotal: { kcal: 259, proteina: 13.5, cho: 11.9, grasa: 23.7 },
        alimentos: [
          { nombre: "Queso mozzarella", cantidad: "55", kcal: 163, proteina: 12.6, cho: 11.8, grasa: 1.7, esLibre: false },
          { nombre: "Uvas verdes", cantidad: "100", kcal: 51, proteina: 0.4, cho: 0, grasa: 12.1, esLibre: false },
          { nombre: "Piña cruda", cantidad: "80", kcal: 45, proteina: 0.5, cho: 0.1, grasa: 9.9, esLibre: false },
        ],
      },
      {
        numero: "Comida 4",
        nombre: "Lomo de cerdo con papa y brocolí",
        subtotal: { kcal: 573, proteina: 68.4, cho: 13.1, grasa: 39.6 },
        alimentos: [
          { nombre: "Lomo de cerdo cocido", cantidad: "160", kcal: 272, proteina: 56.2, cho: 5.1, grasa: 0.3, esLibre: false },
          { nombre: "Papa sabanera cocida", cantidad: "90", kcal: 89, proteina: 2.1, cho: 0.1, grasa: 18.9, esLibre: false },
          { nombre: "Brócoli cocido", cantidad: "200", kcal: 92, proteina: 6.0, cho: 0.6, grasa: 13.2, esLibre: false },
          { nombre: "Espinaca cocida", cantidad: "120", kcal: 41, proteina: 3.5, cho: 0.2, grasa: 4.6, esLibre: false },
          { nombre: "Cebolla cabezona", cantidad: "50", kcal: 16, proteina: 0.6, cho: 0.1, grasa: 2.6, esLibre: false },
          { nombre: "Aceite de oliva", cantidad: "7", kcal: 63, proteina: 0, cho: 7.0, grasa: 0, esLibre: false },
        ],
      },
    ],
  },
  {
    id: 22,
    nombre: "Menú - Bajos  CHO",
    tag: "CHO Bajos",
    totales: { kcal: 1475, proteina: 148.0, cho: 38.1, grasa: 129.4 },
    comidas: [
      {
        numero: "Comida 1",
        nombre: "Huevos revueltos con avena y fruta",
        subtotal: { kcal: 335, proteina: 19.9, cho: 13.4, grasa: 41.4 },
        alimentos: [
          { nombre: "Avena hojuelas Quaker", cantidad: "35", kcal: 144, proteina: 5.9, cho: 2.6, grasa: 22.4, esLibre: false },
          { nombre: "Huevo de gallina completo", cantidad: "100", kcal: 145, proteina: 13.0, cho: 10.4, grasa: 0, esLibre: false },
          { nombre: "Fresas crudas", cantidad: "120", kcal: 46, proteina: 1.0, cho: 0.4, grasa: 19.0, esLibre: false },
        ],
      },
      {
        numero: "Comida 2",
        nombre: "Pechuga de pollo con brocolí y verdura",
        subtotal: { kcal: 549, proteina: 55.8, cho: 14.7, grasa: 43.1 },
        alimentos: [
          { nombre: "Pechuga de pollo asada", cantidad: "150", kcal: 246, proteina: 44.5, cho: 7.3, grasa: 0.3, esLibre: false },
          { nombre: "Arroz blanco cocido", cantidad: "60", kcal: 97, proteina: 1.4, cho: 1.3, grasa: 19.5, esLibre: false },
          { nombre: "Brócoli cocido", cantidad: "200", kcal: 92, proteina: 6.0, cho: 0.6, grasa: 13.2, esLibre: false },
          { nombre: "Espinaca cocida", cantidad: "100", kcal: 34, proteina: 2.9, cho: 0.2, grasa: 3.8, esLibre: false },
          { nombre: "Pimentón rojo", cantidad: "100", kcal: 35, proteina: 1.0, cho: 0.3, grasa: 6.3, esLibre: false },
          { nombre: "Aceite de oliva", cantidad: "5", kcal: 45, proteina: 0, cho: 5.0, grasa: 0, esLibre: false },
        ],
      },
      {
        numero: "Comida 3",
        nombre: "Atun enlatado  con manzana",
        subtotal: { kcal: 167, proteina: 22.3, cho: 0.4, grasa: 16.5 },
        alimentos: [
          { nombre: "Atún Vikingos (enlatado)", cantidad: "100", kcal: 95, proteina: 22.0, cho: 0.2, grasa: 0, esLibre: false },
          { nombre: "Manzana verde", cantidad: "100", kcal: 72, proteina: 0.3, cho: 0.2, grasa: 16.5, esLibre: false },
        ],
      },
      {
        numero: "Comida 4",
        nombre: "Tilapia con champiñones y verduras",
        subtotal: { kcal: 424, proteina: 50.0, cho: 9.6, grasa: 28.4 },
        alimentos: [
          { nombre: "Tilapia cocida", cantidad: "200", kcal: 192, proteina: 40.2, cho: 3.4, grasa: 0, esLibre: false },
          { nombre: "Champiñones en conserva", cantidad: "150", kcal: 65, proteina: 2.9, cho: 0.6, grasa: 9.9, esLibre: false },
          { nombre: "Espinaca cocida", cantidad: "150", kcal: 51, proteina: 4.3, cho: 0.3, grasa: 5.7, esLibre: false },
          { nombre: "Tomate crudo", cantidad: "100", kcal: 55, proteina: 2.0, cho: 0.2, grasa: 10.2, esLibre: false },
          { nombre: "Cebolla cabezona", cantidad: "50", kcal: 16, proteina: 0.6, cho: 0.1, grasa: 2.6, esLibre: false },
          { nombre: "Aceite de oliva", cantidad: "5", kcal: 45, proteina: 0, cho: 5.0, grasa: 0, esLibre: false },
        ],
      },
    ],
  },
  {
    id: 23,
    nombre: "Menú - Bajos  CHO",
    tag: "CHO Bajos",
    totales: { kcal: 1610, proteina: 134.1, cho: 65.6, grasa: 115.1 },
    comidas: [
      {
        numero: "Comida 1",
        nombre: "Huevos revueltos con Aguacate, tomate y champiñones",
        subtotal: { kcal: 477, proteina: 25.0, cho: 26.2, grasa: 29.9 },
        alimentos: [
          { nombre: "Huevo de gallina completo", cantidad: "150", kcal: 218, proteina: 19.5, cho: 15.6, grasa: 0, esLibre: false },
          { nombre: "Aguacate Hass", cantidad: "60", kcal: 133, proteina: 0.8, cho: 9.8, grasa: 8.1, esLibre: false },
          { nombre: "Tomate crudo", cantidad: "100", kcal: 55, proteina: 2.0, cho: 0.2, grasa: 10.2, esLibre: false },
          { nombre: "Champiñones en conserva", cantidad: "100", kcal: 43, proteina: 1.9, cho: 0.4, grasa: 6.6, esLibre: false },
          { nombre: "Pimentón rojo", cantidad: "80", kcal: 28, proteina: 0.8, cho: 0.2, grasa: 5.0, esLibre: false },
        ],
      },
      {
        numero: "Comida 2",
        nombre: "Lomo de cerdo con brocolí y verdura",
        subtotal: { kcal: 526, proteina: 66.0, cho: 12.3, grasa: 31.4 },
        alimentos: [
          { nombre: "Lomo de cerdo cocido", cantidad: "150", kcal: 255, proteina: 52.6, cho: 4.8, grasa: 0.3, esLibre: false },
          { nombre: "Brócoli cocido", cantidad: "250", kcal: 115, proteina: 7.5, cho: 0.8, grasa: 16.5, esLibre: false },
          { nombre: "Espinaca cocida", cantidad: "150", kcal: 51, proteina: 4.3, cho: 0.3, grasa: 5.7, esLibre: false },
          { nombre: "Pimentón rojo", cantidad: "100", kcal: 35, proteina: 1.0, cho: 0.3, grasa: 6.3, esLibre: false },
          { nombre: "Cebolla cabezona", cantidad: "50", kcal: 16, proteina: 0.6, cho: 0.1, grasa: 2.6, esLibre: false },
          { nombre: "Aceite de oliva", cantidad: "6", kcal: 54, proteina: 0, cho: 6.0, grasa: 0, esLibre: false },
        ],
      },
      {
        numero: "Comida 3",
        nombre: "Frutos secos con fruta",
        subtotal: { kcal: 166, proteina: 3.4, cho: 12.7, grasa: 22.6 },
        alimentos: [
          { nombre: "Almendras", cantidad: "20", kcal: 117, proteina: 2.4, cho: 12.3, grasa: 2.1, esLibre: false },
          { nombre: "Fresas crudas", cantidad: "130", kcal: 49, proteina: 1.0, cho: 0.4, grasa: 20.5, esLibre: false },
        ],
      },
      {
        numero: "Comida 4",
        nombre: "Bowl de atún con champiñones y verdura",
        subtotal: { kcal: 441, proteina: 39.7, cho: 14.4, grasa: 31.2 },
        alimentos: [
          { nombre: "Atún Isabel (enlatado)", cantidad: "120", kcal: 137, proteina: 30.0, cho: 1.7, grasa: 0, esLibre: false },
          { nombre: "Champiñones en conserva", cantidad: "150", kcal: 65, proteina: 2.9, cho: 0.6, grasa: 9.9, esLibre: false },
          { nombre: "Espinaca cocida", cantidad: "150", kcal: 51, proteina: 4.3, cho: 0.3, grasa: 5.7, esLibre: false },
          { nombre: "Tomate crudo", cantidad: "100", kcal: 55, proteina: 2.0, cho: 0.2, grasa: 10.2, esLibre: false },
          { nombre: "Aguacate Hass", cantidad: "40", kcal: 88, proteina: 0.5, cho: 6.6, grasa: 5.4, esLibre: false },
          { nombre: "Aceite de oliva", cantidad: "5", kcal: 45, proteina: 0, cho: 5.0, grasa: 0, esLibre: false },
        ],
      },
    ],
  }
] as const
export type MenuPlan = typeof MENUS_PLAN[number]
